# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['BrowserControlPolicyArgs', 'BrowserControlPolicy']

@pulumi.input_type
class BrowserControlPolicyArgs:
    def __init__(__self__, *,
                 allow_all_browsers: Optional[pulumi.Input[_builtins.bool]] = None,
                 blocked_chrome_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 blocked_firefox_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 blocked_internet_explorer_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 blocked_opera_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 blocked_safari_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 bypass_all_browsers: Optional[pulumi.Input[_builtins.bool]] = None,
                 bypass_applications: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 bypass_plugins: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 enable_smart_browser_isolation: Optional[pulumi.Input[_builtins.bool]] = None,
                 enable_warnings: Optional[pulumi.Input[_builtins.bool]] = None,
                 plugin_check_frequency: Optional[pulumi.Input[_builtins.str]] = None,
                 smart_isolation_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 smart_isolation_profile: Optional[pulumi.Input['SmartIsolationProfileInputArgs']] = None,
                 smart_isolation_users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None):
        """
        The set of arguments for constructing a BrowserControlPolicy resource.
        :param pulumi.Input[_builtins.bool] allow_all_browsers: Whether to allow all browsers.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] blocked_chrome_versions: List of blocked Chrome versions.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] blocked_firefox_versions: List of blocked Firefox versions.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] blocked_internet_explorer_versions: List of blocked Internet Explorer versions.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] blocked_opera_versions: List of blocked Opera versions.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] blocked_safari_versions: List of blocked Safari versions.
        :param pulumi.Input[_builtins.bool] bypass_all_browsers: Whether to bypass all browsers.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] bypass_applications: List of applications to bypass.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] bypass_plugins: List of plugins to bypass.
        :param pulumi.Input[_builtins.bool] enable_smart_browser_isolation: Whether to enable Smart Browser Isolation.
        :param pulumi.Input[_builtins.bool] enable_warnings: Whether to enable browser warnings for unsupported browsers.
        :param pulumi.Input[_builtins.str] plugin_check_frequency: How often to check for browser plugins. Valid values: `NEVER`, `ALWAYS`, `DAILY`, `WEEKLY`, `MONTHLY`.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.int]]] smart_isolation_groups: IDs of groups for Smart Browser Isolation.
        :param pulumi.Input['SmartIsolationProfileInputArgs'] smart_isolation_profile: The Cloud Browser Isolation profile to use for Smart Browser Isolation.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.int]]] smart_isolation_users: IDs of users for Smart Browser Isolation.
        """
        if allow_all_browsers is not None:
            pulumi.set(__self__, "allow_all_browsers", allow_all_browsers)
        if blocked_chrome_versions is not None:
            pulumi.set(__self__, "blocked_chrome_versions", blocked_chrome_versions)
        if blocked_firefox_versions is not None:
            pulumi.set(__self__, "blocked_firefox_versions", blocked_firefox_versions)
        if blocked_internet_explorer_versions is not None:
            pulumi.set(__self__, "blocked_internet_explorer_versions", blocked_internet_explorer_versions)
        if blocked_opera_versions is not None:
            pulumi.set(__self__, "blocked_opera_versions", blocked_opera_versions)
        if blocked_safari_versions is not None:
            pulumi.set(__self__, "blocked_safari_versions", blocked_safari_versions)
        if bypass_all_browsers is not None:
            pulumi.set(__self__, "bypass_all_browsers", bypass_all_browsers)
        if bypass_applications is not None:
            pulumi.set(__self__, "bypass_applications", bypass_applications)
        if bypass_plugins is not None:
            pulumi.set(__self__, "bypass_plugins", bypass_plugins)
        if enable_smart_browser_isolation is not None:
            pulumi.set(__self__, "enable_smart_browser_isolation", enable_smart_browser_isolation)
        if enable_warnings is not None:
            pulumi.set(__self__, "enable_warnings", enable_warnings)
        if plugin_check_frequency is not None:
            pulumi.set(__self__, "plugin_check_frequency", plugin_check_frequency)
        if smart_isolation_groups is not None:
            pulumi.set(__self__, "smart_isolation_groups", smart_isolation_groups)
        if smart_isolation_profile is not None:
            pulumi.set(__self__, "smart_isolation_profile", smart_isolation_profile)
        if smart_isolation_users is not None:
            pulumi.set(__self__, "smart_isolation_users", smart_isolation_users)

    @_builtins.property
    @pulumi.getter(name="allowAllBrowsers")
    def allow_all_browsers(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether to allow all browsers.
        """
        return pulumi.get(self, "allow_all_browsers")

    @allow_all_browsers.setter
    def allow_all_browsers(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "allow_all_browsers", value)

    @_builtins.property
    @pulumi.getter(name="blockedChromeVersions")
    def blocked_chrome_versions(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of blocked Chrome versions.
        """
        return pulumi.get(self, "blocked_chrome_versions")

    @blocked_chrome_versions.setter
    def blocked_chrome_versions(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "blocked_chrome_versions", value)

    @_builtins.property
    @pulumi.getter(name="blockedFirefoxVersions")
    def blocked_firefox_versions(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of blocked Firefox versions.
        """
        return pulumi.get(self, "blocked_firefox_versions")

    @blocked_firefox_versions.setter
    def blocked_firefox_versions(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "blocked_firefox_versions", value)

    @_builtins.property
    @pulumi.getter(name="blockedInternetExplorerVersions")
    def blocked_internet_explorer_versions(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of blocked Internet Explorer versions.
        """
        return pulumi.get(self, "blocked_internet_explorer_versions")

    @blocked_internet_explorer_versions.setter
    def blocked_internet_explorer_versions(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "blocked_internet_explorer_versions", value)

    @_builtins.property
    @pulumi.getter(name="blockedOperaVersions")
    def blocked_opera_versions(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of blocked Opera versions.
        """
        return pulumi.get(self, "blocked_opera_versions")

    @blocked_opera_versions.setter
    def blocked_opera_versions(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "blocked_opera_versions", value)

    @_builtins.property
    @pulumi.getter(name="blockedSafariVersions")
    def blocked_safari_versions(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of blocked Safari versions.
        """
        return pulumi.get(self, "blocked_safari_versions")

    @blocked_safari_versions.setter
    def blocked_safari_versions(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "blocked_safari_versions", value)

    @_builtins.property
    @pulumi.getter(name="bypassAllBrowsers")
    def bypass_all_browsers(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether to bypass all browsers.
        """
        return pulumi.get(self, "bypass_all_browsers")

    @bypass_all_browsers.setter
    def bypass_all_browsers(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "bypass_all_browsers", value)

    @_builtins.property
    @pulumi.getter(name="bypassApplications")
    def bypass_applications(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of applications to bypass.
        """
        return pulumi.get(self, "bypass_applications")

    @bypass_applications.setter
    def bypass_applications(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "bypass_applications", value)

    @_builtins.property
    @pulumi.getter(name="bypassPlugins")
    def bypass_plugins(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of plugins to bypass.
        """
        return pulumi.get(self, "bypass_plugins")

    @bypass_plugins.setter
    def bypass_plugins(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "bypass_plugins", value)

    @_builtins.property
    @pulumi.getter(name="enableSmartBrowserIsolation")
    def enable_smart_browser_isolation(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether to enable Smart Browser Isolation.
        """
        return pulumi.get(self, "enable_smart_browser_isolation")

    @enable_smart_browser_isolation.setter
    def enable_smart_browser_isolation(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enable_smart_browser_isolation", value)

    @_builtins.property
    @pulumi.getter(name="enableWarnings")
    def enable_warnings(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether to enable browser warnings for unsupported browsers.
        """
        return pulumi.get(self, "enable_warnings")

    @enable_warnings.setter
    def enable_warnings(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enable_warnings", value)

    @_builtins.property
    @pulumi.getter(name="pluginCheckFrequency")
    def plugin_check_frequency(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        How often to check for browser plugins. Valid values: `NEVER`, `ALWAYS`, `DAILY`, `WEEKLY`, `MONTHLY`.
        """
        return pulumi.get(self, "plugin_check_frequency")

    @plugin_check_frequency.setter
    def plugin_check_frequency(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "plugin_check_frequency", value)

    @_builtins.property
    @pulumi.getter(name="smartIsolationGroups")
    def smart_isolation_groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]:
        """
        IDs of groups for Smart Browser Isolation.
        """
        return pulumi.get(self, "smart_isolation_groups")

    @smart_isolation_groups.setter
    def smart_isolation_groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "smart_isolation_groups", value)

    @_builtins.property
    @pulumi.getter(name="smartIsolationProfile")
    def smart_isolation_profile(self) -> Optional[pulumi.Input['SmartIsolationProfileInputArgs']]:
        """
        The Cloud Browser Isolation profile to use for Smart Browser Isolation.
        """
        return pulumi.get(self, "smart_isolation_profile")

    @smart_isolation_profile.setter
    def smart_isolation_profile(self, value: Optional[pulumi.Input['SmartIsolationProfileInputArgs']]):
        pulumi.set(self, "smart_isolation_profile", value)

    @_builtins.property
    @pulumi.getter(name="smartIsolationUsers")
    def smart_isolation_users(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]:
        """
        IDs of users for Smart Browser Isolation.
        """
        return pulumi.get(self, "smart_isolation_users")

    @smart_isolation_users.setter
    def smart_isolation_users(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "smart_isolation_users", value)


@pulumi.type_token("zia:index:BrowserControlPolicy")
class BrowserControlPolicy(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_all_browsers: Optional[pulumi.Input[_builtins.bool]] = None,
                 blocked_chrome_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 blocked_firefox_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 blocked_internet_explorer_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 blocked_opera_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 blocked_safari_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 bypass_all_browsers: Optional[pulumi.Input[_builtins.bool]] = None,
                 bypass_applications: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 bypass_plugins: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 enable_smart_browser_isolation: Optional[pulumi.Input[_builtins.bool]] = None,
                 enable_warnings: Optional[pulumi.Input[_builtins.bool]] = None,
                 plugin_check_frequency: Optional[pulumi.Input[_builtins.str]] = None,
                 smart_isolation_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 smart_isolation_profile: Optional[pulumi.Input[Union['SmartIsolationProfileInputArgs', 'SmartIsolationProfileInputArgsDict']]] = None,
                 smart_isolation_users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 __props__=None):
        """
        The zia_browser_control_policy resource manages browser control policy settings in the Zscaler Internet Access (ZIA) cloud service. This is a singleton resource — only one browser control policy exists per tenant. Deleting the Pulumi resource does not remove the underlying settings.

        ## Example Usage
        ### Browser Control Policy

        ```python
        import zscaler_pulumi_zia as zia

        example = zia.BrowserControlPolicy("example",
            allow_all_browsers=True,
            enable_warnings=True,
            enable_smart_browser_isolation=False,
        )
        ```

        ## Import

        This is a singleton resource. Import is not applicable because there is no unique API identifier.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] allow_all_browsers: Whether to allow all browsers.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] blocked_chrome_versions: List of blocked Chrome versions.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] blocked_firefox_versions: List of blocked Firefox versions.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] blocked_internet_explorer_versions: List of blocked Internet Explorer versions.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] blocked_opera_versions: List of blocked Opera versions.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] blocked_safari_versions: List of blocked Safari versions.
        :param pulumi.Input[_builtins.bool] bypass_all_browsers: Whether to bypass all browsers.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] bypass_applications: List of applications to bypass.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] bypass_plugins: List of plugins to bypass.
        :param pulumi.Input[_builtins.bool] enable_smart_browser_isolation: Whether to enable Smart Browser Isolation.
        :param pulumi.Input[_builtins.bool] enable_warnings: Whether to enable browser warnings for unsupported browsers.
        :param pulumi.Input[_builtins.str] plugin_check_frequency: How often to check for browser plugins. Valid values: `NEVER`, `ALWAYS`, `DAILY`, `WEEKLY`, `MONTHLY`.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.int]]] smart_isolation_groups: IDs of groups for Smart Browser Isolation.
        :param pulumi.Input[Union['SmartIsolationProfileInputArgs', 'SmartIsolationProfileInputArgsDict']] smart_isolation_profile: The Cloud Browser Isolation profile to use for Smart Browser Isolation.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.int]]] smart_isolation_users: IDs of users for Smart Browser Isolation.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[BrowserControlPolicyArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        The zia_browser_control_policy resource manages browser control policy settings in the Zscaler Internet Access (ZIA) cloud service. This is a singleton resource — only one browser control policy exists per tenant. Deleting the Pulumi resource does not remove the underlying settings.

        ## Example Usage
        ### Browser Control Policy

        ```python
        import zscaler_pulumi_zia as zia

        example = zia.BrowserControlPolicy("example",
            allow_all_browsers=True,
            enable_warnings=True,
            enable_smart_browser_isolation=False,
        )
        ```

        ## Import

        This is a singleton resource. Import is not applicable because there is no unique API identifier.

        :param str resource_name: The name of the resource.
        :param BrowserControlPolicyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(BrowserControlPolicyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_all_browsers: Optional[pulumi.Input[_builtins.bool]] = None,
                 blocked_chrome_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 blocked_firefox_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 blocked_internet_explorer_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 blocked_opera_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 blocked_safari_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 bypass_all_browsers: Optional[pulumi.Input[_builtins.bool]] = None,
                 bypass_applications: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 bypass_plugins: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 enable_smart_browser_isolation: Optional[pulumi.Input[_builtins.bool]] = None,
                 enable_warnings: Optional[pulumi.Input[_builtins.bool]] = None,
                 plugin_check_frequency: Optional[pulumi.Input[_builtins.str]] = None,
                 smart_isolation_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 smart_isolation_profile: Optional[pulumi.Input[Union['SmartIsolationProfileInputArgs', 'SmartIsolationProfileInputArgsDict']]] = None,
                 smart_isolation_users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = BrowserControlPolicyArgs.__new__(BrowserControlPolicyArgs)

            __props__.__dict__["allow_all_browsers"] = allow_all_browsers
            __props__.__dict__["blocked_chrome_versions"] = blocked_chrome_versions
            __props__.__dict__["blocked_firefox_versions"] = blocked_firefox_versions
            __props__.__dict__["blocked_internet_explorer_versions"] = blocked_internet_explorer_versions
            __props__.__dict__["blocked_opera_versions"] = blocked_opera_versions
            __props__.__dict__["blocked_safari_versions"] = blocked_safari_versions
            __props__.__dict__["bypass_all_browsers"] = bypass_all_browsers
            __props__.__dict__["bypass_applications"] = bypass_applications
            __props__.__dict__["bypass_plugins"] = bypass_plugins
            __props__.__dict__["enable_smart_browser_isolation"] = enable_smart_browser_isolation
            __props__.__dict__["enable_warnings"] = enable_warnings
            __props__.__dict__["plugin_check_frequency"] = plugin_check_frequency
            __props__.__dict__["smart_isolation_groups"] = smart_isolation_groups
            __props__.__dict__["smart_isolation_profile"] = smart_isolation_profile
            __props__.__dict__["smart_isolation_users"] = smart_isolation_users
        super(BrowserControlPolicy, __self__).__init__(
            'zia:index:BrowserControlPolicy',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'BrowserControlPolicy':
        """
        Get an existing BrowserControlPolicy resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = BrowserControlPolicyArgs.__new__(BrowserControlPolicyArgs)

        __props__.__dict__["allow_all_browsers"] = None
        __props__.__dict__["blocked_chrome_versions"] = None
        __props__.__dict__["blocked_firefox_versions"] = None
        __props__.__dict__["blocked_internet_explorer_versions"] = None
        __props__.__dict__["blocked_opera_versions"] = None
        __props__.__dict__["blocked_safari_versions"] = None
        __props__.__dict__["bypass_all_browsers"] = None
        __props__.__dict__["bypass_applications"] = None
        __props__.__dict__["bypass_plugins"] = None
        __props__.__dict__["enable_smart_browser_isolation"] = None
        __props__.__dict__["enable_warnings"] = None
        __props__.__dict__["plugin_check_frequency"] = None
        __props__.__dict__["smart_isolation_groups"] = None
        __props__.__dict__["smart_isolation_profile"] = None
        __props__.__dict__["smart_isolation_users"] = None
        return BrowserControlPolicy(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="allowAllBrowsers")
    def allow_all_browsers(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to allow all browsers.
        """
        return pulumi.get(self, "allow_all_browsers")

    @_builtins.property
    @pulumi.getter(name="blockedChromeVersions")
    def blocked_chrome_versions(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of blocked Chrome versions.
        """
        return pulumi.get(self, "blocked_chrome_versions")

    @_builtins.property
    @pulumi.getter(name="blockedFirefoxVersions")
    def blocked_firefox_versions(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of blocked Firefox versions.
        """
        return pulumi.get(self, "blocked_firefox_versions")

    @_builtins.property
    @pulumi.getter(name="blockedInternetExplorerVersions")
    def blocked_internet_explorer_versions(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of blocked Internet Explorer versions.
        """
        return pulumi.get(self, "blocked_internet_explorer_versions")

    @_builtins.property
    @pulumi.getter(name="blockedOperaVersions")
    def blocked_opera_versions(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of blocked Opera versions.
        """
        return pulumi.get(self, "blocked_opera_versions")

    @_builtins.property
    @pulumi.getter(name="blockedSafariVersions")
    def blocked_safari_versions(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of blocked Safari versions.
        """
        return pulumi.get(self, "blocked_safari_versions")

    @_builtins.property
    @pulumi.getter(name="bypassAllBrowsers")
    def bypass_all_browsers(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to bypass all browsers.
        """
        return pulumi.get(self, "bypass_all_browsers")

    @_builtins.property
    @pulumi.getter(name="bypassApplications")
    def bypass_applications(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of applications to bypass.
        """
        return pulumi.get(self, "bypass_applications")

    @_builtins.property
    @pulumi.getter(name="bypassPlugins")
    def bypass_plugins(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of plugins to bypass.
        """
        return pulumi.get(self, "bypass_plugins")

    @_builtins.property
    @pulumi.getter(name="enableSmartBrowserIsolation")
    def enable_smart_browser_isolation(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to enable Smart Browser Isolation.
        """
        return pulumi.get(self, "enable_smart_browser_isolation")

    @_builtins.property
    @pulumi.getter(name="enableWarnings")
    def enable_warnings(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to enable browser warnings for unsupported browsers.
        """
        return pulumi.get(self, "enable_warnings")

    @_builtins.property
    @pulumi.getter(name="pluginCheckFrequency")
    def plugin_check_frequency(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        How often to check for browser plugins. Valid values: `NEVER`, `ALWAYS`, `DAILY`, `WEEKLY`, `MONTHLY`.
        """
        return pulumi.get(self, "plugin_check_frequency")

    @_builtins.property
    @pulumi.getter(name="smartIsolationGroups")
    def smart_isolation_groups(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        """
        IDs of groups for Smart Browser Isolation.
        """
        return pulumi.get(self, "smart_isolation_groups")

    @_builtins.property
    @pulumi.getter(name="smartIsolationProfile")
    def smart_isolation_profile(self) -> pulumi.Output[Optional['outputs.SmartIsolationProfileInput']]:
        """
        The Cloud Browser Isolation profile to use for Smart Browser Isolation.
        """
        return pulumi.get(self, "smart_isolation_profile")

    @_builtins.property
    @pulumi.getter(name="smartIsolationUsers")
    def smart_isolation_users(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        """
        IDs of users for Smart Browser Isolation.
        """
        return pulumi.get(self, "smart_isolation_users")

