# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['FirewallDNSRuleArgs', 'FirewallDNSRule']

@pulumi.input_type
class FirewallDNSRuleArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 order: pulumi.Input[_builtins.int],
                 action: Optional[pulumi.Input[_builtins.str]] = None,
                 applications: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 block_response_code: Optional[pulumi.Input[_builtins.str]] = None,
                 capture_pcap: Optional[pulumi.Input[_builtins.bool]] = None,
                 default_rule: Optional[pulumi.Input[_builtins.bool]] = None,
                 departments: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 dest_addresses: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 dest_countries: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 dest_ip_categories: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 dest_ip_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 dest_ipv6_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 device_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 devices: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 dns_gateway: Optional[pulumi.Input[_builtins.int]] = None,
                 dns_rule_request_types: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 edns_ecs_object: Optional[pulumi.Input[_builtins.int]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 is_web_eun_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 labels: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 location_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 predefined: Optional[pulumi.Input[_builtins.bool]] = None,
                 protocols: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 rank: Optional[pulumi.Input[_builtins.int]] = None,
                 redirect_ip: Optional[pulumi.Input[_builtins.str]] = None,
                 res_categories: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 source_countries: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 src_ip_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 src_ips: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 src_ipv6_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 state: Optional[pulumi.Input[_builtins.str]] = None,
                 time_windows: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 zpa_ip_group: Optional[pulumi.Input[_builtins.int]] = None):
        """
        The set of arguments for constructing a FirewallDNSRule resource.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "order", order)
        if action is not None:
            pulumi.set(__self__, "action", action)
        if applications is not None:
            pulumi.set(__self__, "applications", applications)
        if block_response_code is not None:
            pulumi.set(__self__, "block_response_code", block_response_code)
        if capture_pcap is not None:
            pulumi.set(__self__, "capture_pcap", capture_pcap)
        if default_rule is not None:
            pulumi.set(__self__, "default_rule", default_rule)
        if departments is not None:
            pulumi.set(__self__, "departments", departments)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if dest_addresses is not None:
            pulumi.set(__self__, "dest_addresses", dest_addresses)
        if dest_countries is not None:
            pulumi.set(__self__, "dest_countries", dest_countries)
        if dest_ip_categories is not None:
            pulumi.set(__self__, "dest_ip_categories", dest_ip_categories)
        if dest_ip_groups is not None:
            pulumi.set(__self__, "dest_ip_groups", dest_ip_groups)
        if dest_ipv6_groups is not None:
            pulumi.set(__self__, "dest_ipv6_groups", dest_ipv6_groups)
        if device_groups is not None:
            pulumi.set(__self__, "device_groups", device_groups)
        if devices is not None:
            pulumi.set(__self__, "devices", devices)
        if dns_gateway is not None:
            pulumi.set(__self__, "dns_gateway", dns_gateway)
        if dns_rule_request_types is not None:
            pulumi.set(__self__, "dns_rule_request_types", dns_rule_request_types)
        if edns_ecs_object is not None:
            pulumi.set(__self__, "edns_ecs_object", edns_ecs_object)
        if groups is not None:
            pulumi.set(__self__, "groups", groups)
        if is_web_eun_enabled is not None:
            pulumi.set(__self__, "is_web_eun_enabled", is_web_eun_enabled)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if location_groups is not None:
            pulumi.set(__self__, "location_groups", location_groups)
        if locations is not None:
            pulumi.set(__self__, "locations", locations)
        if predefined is not None:
            pulumi.set(__self__, "predefined", predefined)
        if protocols is not None:
            pulumi.set(__self__, "protocols", protocols)
        if rank is not None:
            pulumi.set(__self__, "rank", rank)
        if redirect_ip is not None:
            pulumi.set(__self__, "redirect_ip", redirect_ip)
        if res_categories is not None:
            pulumi.set(__self__, "res_categories", res_categories)
        if source_countries is not None:
            pulumi.set(__self__, "source_countries", source_countries)
        if src_ip_groups is not None:
            pulumi.set(__self__, "src_ip_groups", src_ip_groups)
        if src_ips is not None:
            pulumi.set(__self__, "src_ips", src_ips)
        if src_ipv6_groups is not None:
            pulumi.set(__self__, "src_ipv6_groups", src_ipv6_groups)
        if state is not None:
            pulumi.set(__self__, "state", state)
        if time_windows is not None:
            pulumi.set(__self__, "time_windows", time_windows)
        if users is not None:
            pulumi.set(__self__, "users", users)
        if zpa_ip_group is not None:
            pulumi.set(__self__, "zpa_ip_group", zpa_ip_group)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def order(self) -> pulumi.Input[_builtins.int]:
        return pulumi.get(self, "order")

    @order.setter
    def order(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "order", value)

    @_builtins.property
    @pulumi.getter
    def action(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "action", value)

    @_builtins.property
    @pulumi.getter
    def applications(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "applications")

    @applications.setter
    def applications(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "applications", value)

    @_builtins.property
    @pulumi.getter(name="blockResponseCode")
    def block_response_code(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "block_response_code")

    @block_response_code.setter
    def block_response_code(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "block_response_code", value)

    @_builtins.property
    @pulumi.getter(name="capturePcap")
    def capture_pcap(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "capture_pcap")

    @capture_pcap.setter
    def capture_pcap(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "capture_pcap", value)

    @_builtins.property
    @pulumi.getter(name="defaultRule")
    def default_rule(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "default_rule")

    @default_rule.setter
    def default_rule(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "default_rule", value)

    @_builtins.property
    @pulumi.getter
    def departments(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]:
        return pulumi.get(self, "departments")

    @departments.setter
    def departments(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "departments", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="destAddresses")
    def dest_addresses(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "dest_addresses")

    @dest_addresses.setter
    def dest_addresses(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "dest_addresses", value)

    @_builtins.property
    @pulumi.getter(name="destCountries")
    def dest_countries(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "dest_countries")

    @dest_countries.setter
    def dest_countries(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "dest_countries", value)

    @_builtins.property
    @pulumi.getter(name="destIpCategories")
    def dest_ip_categories(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "dest_ip_categories")

    @dest_ip_categories.setter
    def dest_ip_categories(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "dest_ip_categories", value)

    @_builtins.property
    @pulumi.getter(name="destIpGroups")
    def dest_ip_groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]:
        return pulumi.get(self, "dest_ip_groups")

    @dest_ip_groups.setter
    def dest_ip_groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "dest_ip_groups", value)

    @_builtins.property
    @pulumi.getter(name="destIpv6Groups")
    def dest_ipv6_groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]:
        return pulumi.get(self, "dest_ipv6_groups")

    @dest_ipv6_groups.setter
    def dest_ipv6_groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "dest_ipv6_groups", value)

    @_builtins.property
    @pulumi.getter(name="deviceGroups")
    def device_groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]:
        return pulumi.get(self, "device_groups")

    @device_groups.setter
    def device_groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "device_groups", value)

    @_builtins.property
    @pulumi.getter
    def devices(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]:
        return pulumi.get(self, "devices")

    @devices.setter
    def devices(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "devices", value)

    @_builtins.property
    @pulumi.getter(name="dnsGateway")
    def dns_gateway(self) -> Optional[pulumi.Input[_builtins.int]]:
        return pulumi.get(self, "dns_gateway")

    @dns_gateway.setter
    def dns_gateway(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "dns_gateway", value)

    @_builtins.property
    @pulumi.getter(name="dnsRuleRequestTypes")
    def dns_rule_request_types(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "dns_rule_request_types")

    @dns_rule_request_types.setter
    def dns_rule_request_types(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "dns_rule_request_types", value)

    @_builtins.property
    @pulumi.getter(name="ednsEcsObject")
    def edns_ecs_object(self) -> Optional[pulumi.Input[_builtins.int]]:
        return pulumi.get(self, "edns_ecs_object")

    @edns_ecs_object.setter
    def edns_ecs_object(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "edns_ecs_object", value)

    @_builtins.property
    @pulumi.getter
    def groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]:
        return pulumi.get(self, "groups")

    @groups.setter
    def groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "groups", value)

    @_builtins.property
    @pulumi.getter(name="isWebEunEnabled")
    def is_web_eun_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "is_web_eun_enabled")

    @is_web_eun_enabled.setter
    def is_web_eun_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "is_web_eun_enabled", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]:
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter(name="locationGroups")
    def location_groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]:
        return pulumi.get(self, "location_groups")

    @location_groups.setter
    def location_groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "location_groups", value)

    @_builtins.property
    @pulumi.getter
    def locations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]:
        return pulumi.get(self, "locations")

    @locations.setter
    def locations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "locations", value)

    @_builtins.property
    @pulumi.getter
    def predefined(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "predefined")

    @predefined.setter
    def predefined(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "predefined", value)

    @_builtins.property
    @pulumi.getter
    def protocols(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "protocols")

    @protocols.setter
    def protocols(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "protocols", value)

    @_builtins.property
    @pulumi.getter
    def rank(self) -> Optional[pulumi.Input[_builtins.int]]:
        return pulumi.get(self, "rank")

    @rank.setter
    def rank(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "rank", value)

    @_builtins.property
    @pulumi.getter(name="redirectIp")
    def redirect_ip(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "redirect_ip")

    @redirect_ip.setter
    def redirect_ip(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "redirect_ip", value)

    @_builtins.property
    @pulumi.getter(name="resCategories")
    def res_categories(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "res_categories")

    @res_categories.setter
    def res_categories(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "res_categories", value)

    @_builtins.property
    @pulumi.getter(name="sourceCountries")
    def source_countries(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "source_countries")

    @source_countries.setter
    def source_countries(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "source_countries", value)

    @_builtins.property
    @pulumi.getter(name="srcIpGroups")
    def src_ip_groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]:
        return pulumi.get(self, "src_ip_groups")

    @src_ip_groups.setter
    def src_ip_groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "src_ip_groups", value)

    @_builtins.property
    @pulumi.getter(name="srcIps")
    def src_ips(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "src_ips")

    @src_ips.setter
    def src_ips(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "src_ips", value)

    @_builtins.property
    @pulumi.getter(name="srcIpv6Groups")
    def src_ipv6_groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]:
        return pulumi.get(self, "src_ipv6_groups")

    @src_ipv6_groups.setter
    def src_ipv6_groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "src_ipv6_groups", value)

    @_builtins.property
    @pulumi.getter
    def state(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "state", value)

    @_builtins.property
    @pulumi.getter(name="timeWindows")
    def time_windows(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]:
        return pulumi.get(self, "time_windows")

    @time_windows.setter
    def time_windows(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "time_windows", value)

    @_builtins.property
    @pulumi.getter
    def users(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]:
        return pulumi.get(self, "users")

    @users.setter
    def users(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "users", value)

    @_builtins.property
    @pulumi.getter(name="zpaIpGroup")
    def zpa_ip_group(self) -> Optional[pulumi.Input[_builtins.int]]:
        return pulumi.get(self, "zpa_ip_group")

    @zpa_ip_group.setter
    def zpa_ip_group(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "zpa_ip_group", value)


@pulumi.type_token("zia:index:FirewallDNSRule")
class FirewallDNSRule(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 action: Optional[pulumi.Input[_builtins.str]] = None,
                 applications: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 block_response_code: Optional[pulumi.Input[_builtins.str]] = None,
                 capture_pcap: Optional[pulumi.Input[_builtins.bool]] = None,
                 default_rule: Optional[pulumi.Input[_builtins.bool]] = None,
                 departments: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 dest_addresses: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 dest_countries: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 dest_ip_categories: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 dest_ip_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 dest_ipv6_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 device_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 devices: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 dns_gateway: Optional[pulumi.Input[_builtins.int]] = None,
                 dns_rule_request_types: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 edns_ecs_object: Optional[pulumi.Input[_builtins.int]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 is_web_eun_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 labels: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 location_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 order: Optional[pulumi.Input[_builtins.int]] = None,
                 predefined: Optional[pulumi.Input[_builtins.bool]] = None,
                 protocols: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 rank: Optional[pulumi.Input[_builtins.int]] = None,
                 redirect_ip: Optional[pulumi.Input[_builtins.str]] = None,
                 res_categories: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 source_countries: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 src_ip_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 src_ips: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 src_ipv6_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 state: Optional[pulumi.Input[_builtins.str]] = None,
                 time_windows: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 zpa_ip_group: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        """
        Create a FirewallDNSRule resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: FirewallDNSRuleArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a FirewallDNSRule resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param FirewallDNSRuleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(FirewallDNSRuleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 action: Optional[pulumi.Input[_builtins.str]] = None,
                 applications: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 block_response_code: Optional[pulumi.Input[_builtins.str]] = None,
                 capture_pcap: Optional[pulumi.Input[_builtins.bool]] = None,
                 default_rule: Optional[pulumi.Input[_builtins.bool]] = None,
                 departments: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 dest_addresses: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 dest_countries: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 dest_ip_categories: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 dest_ip_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 dest_ipv6_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 device_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 devices: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 dns_gateway: Optional[pulumi.Input[_builtins.int]] = None,
                 dns_rule_request_types: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 edns_ecs_object: Optional[pulumi.Input[_builtins.int]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 is_web_eun_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 labels: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 location_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 order: Optional[pulumi.Input[_builtins.int]] = None,
                 predefined: Optional[pulumi.Input[_builtins.bool]] = None,
                 protocols: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 rank: Optional[pulumi.Input[_builtins.int]] = None,
                 redirect_ip: Optional[pulumi.Input[_builtins.str]] = None,
                 res_categories: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 source_countries: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 src_ip_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 src_ips: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 src_ipv6_groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 state: Optional[pulumi.Input[_builtins.str]] = None,
                 time_windows: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 zpa_ip_group: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = FirewallDNSRuleArgs.__new__(FirewallDNSRuleArgs)

            __props__.__dict__["action"] = action
            __props__.__dict__["applications"] = applications
            __props__.__dict__["block_response_code"] = block_response_code
            __props__.__dict__["capture_pcap"] = capture_pcap
            __props__.__dict__["default_rule"] = default_rule
            __props__.__dict__["departments"] = departments
            __props__.__dict__["description"] = description
            __props__.__dict__["dest_addresses"] = dest_addresses
            __props__.__dict__["dest_countries"] = dest_countries
            __props__.__dict__["dest_ip_categories"] = dest_ip_categories
            __props__.__dict__["dest_ip_groups"] = dest_ip_groups
            __props__.__dict__["dest_ipv6_groups"] = dest_ipv6_groups
            __props__.__dict__["device_groups"] = device_groups
            __props__.__dict__["devices"] = devices
            __props__.__dict__["dns_gateway"] = dns_gateway
            __props__.__dict__["dns_rule_request_types"] = dns_rule_request_types
            __props__.__dict__["edns_ecs_object"] = edns_ecs_object
            __props__.__dict__["groups"] = groups
            __props__.__dict__["is_web_eun_enabled"] = is_web_eun_enabled
            __props__.__dict__["labels"] = labels
            __props__.__dict__["location_groups"] = location_groups
            __props__.__dict__["locations"] = locations
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            if order is None and not opts.urn:
                raise TypeError("Missing required property 'order'")
            __props__.__dict__["order"] = order
            __props__.__dict__["predefined"] = predefined
            __props__.__dict__["protocols"] = protocols
            __props__.__dict__["rank"] = rank
            __props__.__dict__["redirect_ip"] = redirect_ip
            __props__.__dict__["res_categories"] = res_categories
            __props__.__dict__["source_countries"] = source_countries
            __props__.__dict__["src_ip_groups"] = src_ip_groups
            __props__.__dict__["src_ips"] = src_ips
            __props__.__dict__["src_ipv6_groups"] = src_ipv6_groups
            __props__.__dict__["state"] = state
            __props__.__dict__["time_windows"] = time_windows
            __props__.__dict__["users"] = users
            __props__.__dict__["zpa_ip_group"] = zpa_ip_group
            __props__.__dict__["rule_id"] = None
        super(FirewallDNSRule, __self__).__init__(
            'zia:index:FirewallDNSRule',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'FirewallDNSRule':
        """
        Get an existing FirewallDNSRule resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = FirewallDNSRuleArgs.__new__(FirewallDNSRuleArgs)

        __props__.__dict__["action"] = None
        __props__.__dict__["applications"] = None
        __props__.__dict__["block_response_code"] = None
        __props__.__dict__["capture_pcap"] = None
        __props__.__dict__["default_rule"] = None
        __props__.__dict__["departments"] = None
        __props__.__dict__["description"] = None
        __props__.__dict__["dest_addresses"] = None
        __props__.__dict__["dest_countries"] = None
        __props__.__dict__["dest_ip_categories"] = None
        __props__.__dict__["dest_ip_groups"] = None
        __props__.__dict__["dest_ipv6_groups"] = None
        __props__.__dict__["device_groups"] = None
        __props__.__dict__["devices"] = None
        __props__.__dict__["dns_gateway"] = None
        __props__.__dict__["dns_rule_request_types"] = None
        __props__.__dict__["edns_ecs_object"] = None
        __props__.__dict__["groups"] = None
        __props__.__dict__["is_web_eun_enabled"] = None
        __props__.__dict__["labels"] = None
        __props__.__dict__["location_groups"] = None
        __props__.__dict__["locations"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["order"] = None
        __props__.__dict__["predefined"] = None
        __props__.__dict__["protocols"] = None
        __props__.__dict__["rank"] = None
        __props__.__dict__["redirect_ip"] = None
        __props__.__dict__["res_categories"] = None
        __props__.__dict__["rule_id"] = None
        __props__.__dict__["source_countries"] = None
        __props__.__dict__["src_ip_groups"] = None
        __props__.__dict__["src_ips"] = None
        __props__.__dict__["src_ipv6_groups"] = None
        __props__.__dict__["state"] = None
        __props__.__dict__["time_windows"] = None
        __props__.__dict__["users"] = None
        __props__.__dict__["zpa_ip_group"] = None
        return FirewallDNSRule(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def action(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "action")

    @_builtins.property
    @pulumi.getter
    def applications(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "applications")

    @_builtins.property
    @pulumi.getter(name="blockResponseCode")
    def block_response_code(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "block_response_code")

    @_builtins.property
    @pulumi.getter(name="capturePcap")
    def capture_pcap(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "capture_pcap")

    @_builtins.property
    @pulumi.getter(name="defaultRule")
    def default_rule(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "default_rule")

    @_builtins.property
    @pulumi.getter
    def departments(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        return pulumi.get(self, "departments")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="destAddresses")
    def dest_addresses(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "dest_addresses")

    @_builtins.property
    @pulumi.getter(name="destCountries")
    def dest_countries(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "dest_countries")

    @_builtins.property
    @pulumi.getter(name="destIpCategories")
    def dest_ip_categories(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "dest_ip_categories")

    @_builtins.property
    @pulumi.getter(name="destIpGroups")
    def dest_ip_groups(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        return pulumi.get(self, "dest_ip_groups")

    @_builtins.property
    @pulumi.getter(name="destIpv6Groups")
    def dest_ipv6_groups(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        return pulumi.get(self, "dest_ipv6_groups")

    @_builtins.property
    @pulumi.getter(name="deviceGroups")
    def device_groups(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        return pulumi.get(self, "device_groups")

    @_builtins.property
    @pulumi.getter
    def devices(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        return pulumi.get(self, "devices")

    @_builtins.property
    @pulumi.getter(name="dnsGateway")
    def dns_gateway(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "dns_gateway")

    @_builtins.property
    @pulumi.getter(name="dnsRuleRequestTypes")
    def dns_rule_request_types(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "dns_rule_request_types")

    @_builtins.property
    @pulumi.getter(name="ednsEcsObject")
    def edns_ecs_object(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "edns_ecs_object")

    @_builtins.property
    @pulumi.getter
    def groups(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        return pulumi.get(self, "groups")

    @_builtins.property
    @pulumi.getter(name="isWebEunEnabled")
    def is_web_eun_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "is_web_eun_enabled")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter(name="locationGroups")
    def location_groups(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        return pulumi.get(self, "location_groups")

    @_builtins.property
    @pulumi.getter
    def locations(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        return pulumi.get(self, "locations")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def order(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "order")

    @_builtins.property
    @pulumi.getter
    def predefined(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "predefined")

    @_builtins.property
    @pulumi.getter
    def protocols(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "protocols")

    @_builtins.property
    @pulumi.getter
    def rank(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "rank")

    @_builtins.property
    @pulumi.getter(name="redirectIp")
    def redirect_ip(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "redirect_ip")

    @_builtins.property
    @pulumi.getter(name="resCategories")
    def res_categories(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "res_categories")

    @_builtins.property
    @pulumi.getter(name="ruleId")
    def rule_id(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "rule_id")

    @_builtins.property
    @pulumi.getter(name="sourceCountries")
    def source_countries(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "source_countries")

    @_builtins.property
    @pulumi.getter(name="srcIpGroups")
    def src_ip_groups(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        return pulumi.get(self, "src_ip_groups")

    @_builtins.property
    @pulumi.getter(name="srcIps")
    def src_ips(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "src_ips")

    @_builtins.property
    @pulumi.getter(name="srcIpv6Groups")
    def src_ipv6_groups(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        return pulumi.get(self, "src_ipv6_groups")

    @_builtins.property
    @pulumi.getter
    def state(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "state")

    @_builtins.property
    @pulumi.getter(name="timeWindows")
    def time_windows(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        return pulumi.get(self, "time_windows")

    @_builtins.property
    @pulumi.getter
    def users(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        return pulumi.get(self, "users")

    @_builtins.property
    @pulumi.getter(name="zpaIpGroup")
    def zpa_ip_group(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "zpa_ip_group")

