# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetDlpDictionaryPredefinedIdentifiersResult',
    'AwaitableGetDlpDictionaryPredefinedIdentifiersResult',
    'get_dlp_dictionary_predefined_identifiers',
    'get_dlp_dictionary_predefined_identifiers_output',
]

@pulumi.output_type
class GetDlpDictionaryPredefinedIdentifiersResult:
    def __init__(__self__, predefined_identifiers=None, resource_id=None):
        if predefined_identifiers and not isinstance(predefined_identifiers, list):
            raise TypeError("Expected argument 'predefined_identifiers' to be a list")
        pulumi.set(__self__, "predefined_identifiers", predefined_identifiers)
        if resource_id and not isinstance(resource_id, str):
            raise TypeError("Expected argument 'resource_id' to be a str")
        pulumi.set(__self__, "resource_id", resource_id)

    @_builtins.property
    @pulumi.getter(name="predefinedIdentifiers")
    def predefined_identifiers(self) -> Sequence[_builtins.str]:
        """
        The list of predefined identifiers for the dictionary.
        """
        return pulumi.get(self, "predefined_identifiers")

    @_builtins.property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> _builtins.str:
        """
        The ID of the predefined DLP dictionary.
        """
        return pulumi.get(self, "resource_id")


class AwaitableGetDlpDictionaryPredefinedIdentifiersResult(GetDlpDictionaryPredefinedIdentifiersResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDlpDictionaryPredefinedIdentifiersResult(
            predefined_identifiers=self.predefined_identifiers,
            resource_id=self.resource_id)


def get_dlp_dictionary_predefined_identifiers(name: Optional[_builtins.str] = None,
                                              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDlpDictionaryPredefinedIdentifiersResult:
    """
    Use this data source to look up predefined DLP dictionary identifiers by dictionary name.


    :param _builtins.str name: The name of the predefined DLP dictionary to look up.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('zia:index:getDlpDictionaryPredefinedIdentifiers', __args__, opts=opts, typ=GetDlpDictionaryPredefinedIdentifiersResult).value

    return AwaitableGetDlpDictionaryPredefinedIdentifiersResult(
        predefined_identifiers=pulumi.get(__ret__, 'predefined_identifiers'),
        resource_id=pulumi.get(__ret__, 'resource_id'))
def get_dlp_dictionary_predefined_identifiers_output(name: Optional[pulumi.Input[_builtins.str]] = None,
                                                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetDlpDictionaryPredefinedIdentifiersResult]:
    """
    Use this data source to look up predefined DLP dictionary identifiers by dictionary name.


    :param _builtins.str name: The name of the predefined DLP dictionary to look up.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('zia:index:getDlpDictionaryPredefinedIdentifiers', __args__, opts=opts, typ=GetDlpDictionaryPredefinedIdentifiersResult)
    return __ret__.apply(lambda __response__: GetDlpDictionaryPredefinedIdentifiersResult(
        predefined_identifiers=pulumi.get(__response__, 'predefined_identifiers'),
        resource_id=pulumi.get(__response__, 'resource_id')))
