# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetDlpIdmProfileLiteResult',
    'AwaitableGetDlpIdmProfileLiteResult',
    'get_dlp_idm_profile_lite',
    'get_dlp_idm_profile_lite_output',
]

@pulumi.output_type
class GetDlpIdmProfileLiteResult:
    def __init__(__self__, client_vm=None, last_modified_by=None, last_modified_time=None, num_documents=None, profile_id=None, template_name=None):
        if client_vm and not isinstance(client_vm, dict):
            raise TypeError("Expected argument 'client_vm' to be a dict")
        pulumi.set(__self__, "client_vm", client_vm)
        if last_modified_by and not isinstance(last_modified_by, dict):
            raise TypeError("Expected argument 'last_modified_by' to be a dict")
        pulumi.set(__self__, "last_modified_by", last_modified_by)
        if last_modified_time and not isinstance(last_modified_time, int):
            raise TypeError("Expected argument 'last_modified_time' to be a int")
        pulumi.set(__self__, "last_modified_time", last_modified_time)
        if num_documents and not isinstance(num_documents, int):
            raise TypeError("Expected argument 'num_documents' to be a int")
        pulumi.set(__self__, "num_documents", num_documents)
        if profile_id and not isinstance(profile_id, int):
            raise TypeError("Expected argument 'profile_id' to be a int")
        pulumi.set(__self__, "profile_id", profile_id)
        if template_name and not isinstance(template_name, str):
            raise TypeError("Expected argument 'template_name' to be a str")
        pulumi.set(__self__, "template_name", template_name)

    @_builtins.property
    @pulumi.getter(name="clientVm")
    def client_vm(self) -> Optional['outputs.IdNameExtensionsOutput']:
        """
        The client VM associated with the profile.
        """
        return pulumi.get(self, "client_vm")

    @_builtins.property
    @pulumi.getter(name="lastModifiedBy")
    def last_modified_by(self) -> Optional['outputs.IdNameExtensionsOutput']:
        """
        The user who last modified the profile.
        """
        return pulumi.get(self, "last_modified_by")

    @_builtins.property
    @pulumi.getter(name="lastModifiedTime")
    def last_modified_time(self) -> _builtins.int:
        """
        The last modification time (epoch).
        """
        return pulumi.get(self, "last_modified_time")

    @_builtins.property
    @pulumi.getter(name="numDocuments")
    def num_documents(self) -> _builtins.int:
        """
        The number of documents in the profile.
        """
        return pulumi.get(self, "num_documents")

    @_builtins.property
    @pulumi.getter(name="profileId")
    def profile_id(self) -> _builtins.int:
        """
        The ID of the DLP IDM profile.
        """
        return pulumi.get(self, "profile_id")

    @_builtins.property
    @pulumi.getter(name="templateName")
    def template_name(self) -> _builtins.str:
        """
        The template name of the DLP IDM profile.
        """
        return pulumi.get(self, "template_name")


class AwaitableGetDlpIdmProfileLiteResult(GetDlpIdmProfileLiteResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDlpIdmProfileLiteResult(
            client_vm=self.client_vm,
            last_modified_by=self.last_modified_by,
            last_modified_time=self.last_modified_time,
            num_documents=self.num_documents,
            profile_id=self.profile_id,
            template_name=self.template_name)


def get_dlp_idm_profile_lite(active_only: Optional[_builtins.bool] = None,
                             profile_id: Optional[_builtins.int] = None,
                             template_name: Optional[_builtins.str] = None,
                             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDlpIdmProfileLiteResult:
    """
    Use this data source to look up a DLP IDM profile (lite) by ID or template name.


    :param _builtins.bool active_only: If true, only return active profiles.
    :param _builtins.int profile_id: The ID of the DLP IDM profile to look up.
    :param _builtins.str template_name: The template name of the DLP IDM profile to look up.
    """
    __args__ = dict()
    __args__['activeOnly'] = active_only
    __args__['profileId'] = profile_id
    __args__['templateName'] = template_name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('zia:index:getDlpIdmProfileLite', __args__, opts=opts, typ=GetDlpIdmProfileLiteResult).value

    return AwaitableGetDlpIdmProfileLiteResult(
        client_vm=pulumi.get(__ret__, 'client_vm'),
        last_modified_by=pulumi.get(__ret__, 'last_modified_by'),
        last_modified_time=pulumi.get(__ret__, 'last_modified_time'),
        num_documents=pulumi.get(__ret__, 'num_documents'),
        profile_id=pulumi.get(__ret__, 'profile_id'),
        template_name=pulumi.get(__ret__, 'template_name'))
def get_dlp_idm_profile_lite_output(active_only: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                                    profile_id: Optional[pulumi.Input[Optional[_builtins.int]]] = None,
                                    template_name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetDlpIdmProfileLiteResult]:
    """
    Use this data source to look up a DLP IDM profile (lite) by ID or template name.


    :param _builtins.bool active_only: If true, only return active profiles.
    :param _builtins.int profile_id: The ID of the DLP IDM profile to look up.
    :param _builtins.str template_name: The template name of the DLP IDM profile to look up.
    """
    __args__ = dict()
    __args__['activeOnly'] = active_only
    __args__['profileId'] = profile_id
    __args__['templateName'] = template_name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('zia:index:getDlpIdmProfileLite', __args__, opts=opts, typ=GetDlpIdmProfileLiteResult)
    return __ret__.apply(lambda __response__: GetDlpIdmProfileLiteResult(
        client_vm=pulumi.get(__response__, 'client_vm'),
        last_modified_by=pulumi.get(__response__, 'last_modified_by'),
        last_modified_time=pulumi.get(__response__, 'last_modified_time'),
        num_documents=pulumi.get(__response__, 'num_documents'),
        profile_id=pulumi.get(__response__, 'profile_id'),
        template_name=pulumi.get(__response__, 'template_name')))
