template: native
provider: zia
major-version: 1
providerDefaultBranch: main
publishRegistry: false
providerVersion: github.com/zscaler/pulumi-zia/provider/version.Version
parallel: 3
sdkModuleDir: sdk/go/pulumi-zia
