version: 2
project_name: pulumi-zia
builds:
- id: build-provider
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  main: ./cmd/pulumi-resource-zia/
  ldflags:
    - -s
    - -w
    - -X
      github.com/zscaler/pulumi-zia/provider/version.Version={{.Tag}}
  binary: pulumi-resource-zia
archives:
- name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  id: archive
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  disable: true
release:
  disable: false
