version: 2
project_name: pulumi-zia
builds:
- id: build-provider
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
  ignore: &a1 []
  main: ./cmd/pulumi-resource-zia/
  ldflags: &a2
    - -s
    - -w
    - -X
      github.com/zscaler/pulumi-zia/provider/version.Version={{.Tag}}
  binary: pulumi-resource-zia
- id: build-provider-sign-windows
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
  - windows
  goarch:
  - amd64
  - arm64
  ignore: *a1
  main: ./cmd/pulumi-resource-zia/
  ldflags: *a2
  binary: pulumi-resource-zia
  hooks:
    post:
    - make sign-goreleaser-exe-{{ .Arch }}
archives:
- name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  id: archive
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  disable: true
release:
  disable: true
