// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.zia.zia.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class CBIProfileInput {
    private @Nullable String name;
    private @Nullable Integer profileSeq;
    private @Nullable String resourceId;
    private @Nullable String url;

    private CBIProfileInput() {}
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    public Optional<Integer> profileSeq() {
        return Optional.ofNullable(this.profileSeq);
    }
    public Optional<String> resourceId() {
        return Optional.ofNullable(this.resourceId);
    }
    public Optional<String> url() {
        return Optional.ofNullable(this.url);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CBIProfileInput defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String name;
        private @Nullable Integer profileSeq;
        private @Nullable String resourceId;
        private @Nullable String url;
        public Builder() {}
        public Builder(CBIProfileInput defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.profileSeq = defaults.profileSeq;
    	      this.resourceId = defaults.resourceId;
    	      this.url = defaults.url;
        }

        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder profileSeq(@Nullable Integer profileSeq) {

            this.profileSeq = profileSeq;
            return this;
        }
        @CustomType.Setter
        public Builder resourceId(@Nullable String resourceId) {

            this.resourceId = resourceId;
            return this;
        }
        @CustomType.Setter
        public Builder url(@Nullable String url) {

            this.url = url;
            return this;
        }
        public CBIProfileInput build() {
            final var _resultValue = new CBIProfileInput();
            _resultValue.name = name;
            _resultValue.profileSeq = profileSeq;
            _resultValue.resourceId = resourceId;
            _resultValue.url = url;
            return _resultValue;
        }
    }
}
