// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.zia.zia.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.zia.zia.outputs.DatacenterInfo;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetDatacentersResult {
    /**
     * @return The datacenter city when exactly one result is returned.
     * 
     */
    private @Nullable String city;
    /**
     * @return The datacenter ID when exactly one result is returned.
     * 
     */
    private @Nullable Integer datacenterId;
    /**
     * @return List of datacenters matching the filter criteria.
     * 
     */
    private List<DatacenterInfo> datacenters;
    /**
     * @return The datacenter name when exactly one result is returned.
     * 
     */
    private @Nullable String name;

    private GetDatacentersResult() {}
    /**
     * @return The datacenter city when exactly one result is returned.
     * 
     */
    public Optional<String> city() {
        return Optional.ofNullable(this.city);
    }
    /**
     * @return The datacenter ID when exactly one result is returned.
     * 
     */
    public Optional<Integer> datacenterId() {
        return Optional.ofNullable(this.datacenterId);
    }
    /**
     * @return List of datacenters matching the filter criteria.
     * 
     */
    public List<DatacenterInfo> datacenters() {
        return this.datacenters;
    }
    /**
     * @return The datacenter name when exactly one result is returned.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDatacentersResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String city;
        private @Nullable Integer datacenterId;
        private List<DatacenterInfo> datacenters;
        private @Nullable String name;
        public Builder() {}
        public Builder(GetDatacentersResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.city = defaults.city;
    	      this.datacenterId = defaults.datacenterId;
    	      this.datacenters = defaults.datacenters;
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder city(@Nullable String city) {

            this.city = city;
            return this;
        }
        @CustomType.Setter
        public Builder datacenterId(@Nullable Integer datacenterId) {

            this.datacenterId = datacenterId;
            return this;
        }
        @CustomType.Setter
        public Builder datacenters(List<DatacenterInfo> datacenters) {
            if (datacenters == null) {
              throw new MissingRequiredPropertyException("GetDatacentersResult", "datacenters");
            }
            this.datacenters = datacenters;
            return this;
        }
        public Builder datacenters(DatacenterInfo... datacenters) {
            return datacenters(List.of(datacenters));
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        public GetDatacentersResult build() {
            final var _resultValue = new GetDatacentersResult();
            _resultValue.city = city;
            _resultValue.datacenterId = datacenterId;
            _resultValue.datacenters = datacenters;
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
