// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.zia.zia.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.zia.zia.outputs.WorkloadGroupExpressionJsonInput;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetWorkloadGroupResult {
    private String description;
    private String expression;
    private @Nullable WorkloadGroupExpressionJsonInput expressionJson;
    private Integer groupId;
    private Integer lastModifiedTime;
    private String name;

    private GetWorkloadGroupResult() {}
    public String description() {
        return this.description;
    }
    public String expression() {
        return this.expression;
    }
    public Optional<WorkloadGroupExpressionJsonInput> expressionJson() {
        return Optional.ofNullable(this.expressionJson);
    }
    public Integer groupId() {
        return this.groupId;
    }
    public Integer lastModifiedTime() {
        return this.lastModifiedTime;
    }
    public String name() {
        return this.name;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetWorkloadGroupResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String description;
        private String expression;
        private @Nullable WorkloadGroupExpressionJsonInput expressionJson;
        private Integer groupId;
        private Integer lastModifiedTime;
        private String name;
        public Builder() {}
        public Builder(GetWorkloadGroupResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.description = defaults.description;
    	      this.expression = defaults.expression;
    	      this.expressionJson = defaults.expressionJson;
    	      this.groupId = defaults.groupId;
    	      this.lastModifiedTime = defaults.lastModifiedTime;
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetWorkloadGroupResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder expression(String expression) {
            if (expression == null) {
              throw new MissingRequiredPropertyException("GetWorkloadGroupResult", "expression");
            }
            this.expression = expression;
            return this;
        }
        @CustomType.Setter
        public Builder expressionJson(@Nullable WorkloadGroupExpressionJsonInput expressionJson) {

            this.expressionJson = expressionJson;
            return this;
        }
        @CustomType.Setter
        public Builder groupId(Integer groupId) {
            if (groupId == null) {
              throw new MissingRequiredPropertyException("GetWorkloadGroupResult", "groupId");
            }
            this.groupId = groupId;
            return this;
        }
        @CustomType.Setter
        public Builder lastModifiedTime(Integer lastModifiedTime) {
            if (lastModifiedTime == null) {
              throw new MissingRequiredPropertyException("GetWorkloadGroupResult", "lastModifiedTime");
            }
            this.lastModifiedTime = lastModifiedTime;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetWorkloadGroupResult", "name");
            }
            this.name = name;
            return this;
        }
        public GetWorkloadGroupResult build() {
            final var _resultValue = new GetWorkloadGroupResult();
            _resultValue.description = description;
            _resultValue.expression = expression;
            _resultValue.expressionJson = expressionJson;
            _resultValue.groupId = groupId;
            _resultValue.lastModifiedTime = lastModifiedTime;
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
