// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zia
{
    /// <summary>
    /// * [Official documentation](https://help.zscaler.com/legacy-apis/traffic-forwarding-0#/extranet-get)
    /// * [API documentation](https://help.zscaler.com/zia/understanding-extranet-application-support)
    /// 
    /// Use the **zia_extranet** resource Adds a new extranet for the organization in the Zscaler Internet Access cloud. Extranets are configured as part of Zscaler Extranet Application Support which allows an organization to connect its internal network with another organization’s network (e.g., partners, third-party vendors, etc.) that does not use the Zscaler service. Extranet Application Support enables Zscaler-managed organization users to securely access extranet resources through an IPSec VPN tunnel established between the Zscaler data center and the external organization’s data center, without requiring additional hardware or software installations.
    /// 
    /// &gt; NOTE: This an Early Access feature.
    /// 
    /// ## Example Usage
    /// 
    /// ### Retrieve By Name
    /// 
    /// ## Import
    /// 
    /// Zscaler offers a dedicated tool called Zscaler-Terraformer to allow the automated import of ZIA configurations into Terraform-compliant HashiCorp Configuration Language.
    /// Visit
    /// 
    /// **zia_extranet** can be imported by using `&lt;EXTRANET ID&gt;` or `&lt;EXTRANET NAME&gt;` as the import ID.
    /// 
    /// For example:
    /// 
    /// ```sh
    /// $ pulumi import zia:index/extranet:Extranet example &lt;extranet_id&gt;
    /// ```
    /// 
    /// or
    /// 
    /// ```sh
    /// $ pulumi import zia:index/extranet:Extranet example &lt;extranet_name&gt;
    /// ```
    /// </summary>
    [ZiaResourceType("zia:index/extranet:Extranet")]
    public partial class Extranet : global::Pulumi.CustomResource
    {
        /// <summary>
        /// (String) The description of the extranet.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// (List) Information about the DNS servers specified for the extranet.
        /// </summary>
        [Output("extranetDnsLists")]
        public Output<ImmutableArray<Outputs.ExtranetExtranetDnsList>> ExtranetDnsLists { get; private set; } = null!;

        [Output("extranetId")]
        public Output<int> ExtranetId { get; private set; } = null!;

        /// <summary>
        /// (List) Information about the traffic selectors (IP pools) specified for the extranet.
        /// </summary>
        [Output("extranetIpPoolLists")]
        public Output<ImmutableArray<Outputs.ExtranetExtranetIpPoolList>> ExtranetIpPoolLists { get; private set; } = null!;

        /// <summary>
        /// (String) The name of the IP pool.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;


        /// <summary>
        /// Create a Extranet resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Extranet(string name, ExtranetArgs? args = null, CustomResourceOptions? options = null)
            : base("zia:index/extranet:Extranet", name, args ?? new ExtranetArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Extranet(string name, Input<string> id, ExtranetState? state = null, CustomResourceOptions? options = null)
            : base("zia:index/extranet:Extranet", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/zscaler",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Extranet resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Extranet Get(string name, Input<string> id, ExtranetState? state = null, CustomResourceOptions? options = null)
        {
            return new Extranet(name, id, state, options);
        }
    }

    public sealed class ExtranetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// (String) The description of the extranet.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("extranetDnsLists")]
        private InputList<Inputs.ExtranetExtranetDnsListArgs>? _extranetDnsLists;

        /// <summary>
        /// (List) Information about the DNS servers specified for the extranet.
        /// </summary>
        public InputList<Inputs.ExtranetExtranetDnsListArgs> ExtranetDnsLists
        {
            get => _extranetDnsLists ?? (_extranetDnsLists = new InputList<Inputs.ExtranetExtranetDnsListArgs>());
            set => _extranetDnsLists = value;
        }

        [Input("extranetIpPoolLists")]
        private InputList<Inputs.ExtranetExtranetIpPoolListArgs>? _extranetIpPoolLists;

        /// <summary>
        /// (List) Information about the traffic selectors (IP pools) specified for the extranet.
        /// </summary>
        public InputList<Inputs.ExtranetExtranetIpPoolListArgs> ExtranetIpPoolLists
        {
            get => _extranetIpPoolLists ?? (_extranetIpPoolLists = new InputList<Inputs.ExtranetExtranetIpPoolListArgs>());
            set => _extranetIpPoolLists = value;
        }

        /// <summary>
        /// (String) The name of the IP pool.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public ExtranetArgs()
        {
        }
        public static new ExtranetArgs Empty => new ExtranetArgs();
    }

    public sealed class ExtranetState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// (String) The description of the extranet.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("extranetDnsLists")]
        private InputList<Inputs.ExtranetExtranetDnsListGetArgs>? _extranetDnsLists;

        /// <summary>
        /// (List) Information about the DNS servers specified for the extranet.
        /// </summary>
        public InputList<Inputs.ExtranetExtranetDnsListGetArgs> ExtranetDnsLists
        {
            get => _extranetDnsLists ?? (_extranetDnsLists = new InputList<Inputs.ExtranetExtranetDnsListGetArgs>());
            set => _extranetDnsLists = value;
        }

        [Input("extranetId")]
        public Input<int>? ExtranetId { get; set; }

        [Input("extranetIpPoolLists")]
        private InputList<Inputs.ExtranetExtranetIpPoolListGetArgs>? _extranetIpPoolLists;

        /// <summary>
        /// (List) Information about the traffic selectors (IP pools) specified for the extranet.
        /// </summary>
        public InputList<Inputs.ExtranetExtranetIpPoolListGetArgs> ExtranetIpPoolLists
        {
            get => _extranetIpPoolLists ?? (_extranetIpPoolLists = new InputList<Inputs.ExtranetExtranetIpPoolListGetArgs>());
            set => _extranetIpPoolLists = value;
        }

        /// <summary>
        /// (String) The name of the IP pool.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public ExtranetState()
        {
        }
        public static new ExtranetState Empty => new ExtranetState();
    }
}
