// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zia

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/zscaler/pulumi-zia/sdk/go/zia/internal"
)

// * [Official documentation](https://help.zscaler.com/zia/firewall-policies#/networkServices-get)
// * [API documentation](https://help.zscaler.com/zia/firewall-policies#/networkServices-get)
//
// The **zia_firewall_filtering_network_service** resource allows the creation and management of ZIA Cloud Firewall IP network services in the Zscaler Internet Access. This resource can then be associated with a ZIA cloud firewall filtering rule and network service group resources.
//
// ## Example Usage
//
// ## Import
//
// Zscaler offers a dedicated tool called Zscaler-Terraformer to allow the automated import of ZIA configurations into Terraform-compliant HashiCorp Configuration Language.
// Visit
//
// **zia_firewall_filtering_network_service** can be imported by using `<SERVICE_ID>` or `<SERVICE_NAME>` as the import ID.
//
// For example:
//
// ```sh
// $ pulumi import zia:index/firewallFilteringNetworkServices:FirewallFilteringNetworkServices example <service_id>
// ```
//
// or
//
// ```sh
// $ pulumi import zia:index/firewallFilteringNetworkServices:FirewallFilteringNetworkServices example <service_name>
// ```
type FirewallFilteringNetworkServices struct {
	pulumi.CustomResourceState

	Description pulumi.StringPtrOutput `pulumi:"description"`
	// dest tcp ports
	DestTcpPorts FirewallFilteringNetworkServicesDestTcpPortArrayOutput `pulumi:"destTcpPorts"`
	// dest udp ports
	DestUdpPorts     FirewallFilteringNetworkServicesDestUdpPortArrayOutput `pulumi:"destUdpPorts"`
	IsNameL10nTag    pulumi.BoolPtrOutput                                   `pulumi:"isNameL10nTag"`
	Name             pulumi.StringOutput                                    `pulumi:"name"`
	NetworkServiceId pulumi.IntOutput                                       `pulumi:"networkServiceId"`
	// src tcp ports
	SrcTcpPorts FirewallFilteringNetworkServicesSrcTcpPortArrayOutput `pulumi:"srcTcpPorts"`
	// src udp ports
	SrcUdpPorts FirewallFilteringNetworkServicesSrcUdpPortArrayOutput `pulumi:"srcUdpPorts"`
	Tag         pulumi.StringOutput                                   `pulumi:"tag"`
	Type        pulumi.StringPtrOutput                                `pulumi:"type"`
}

// NewFirewallFilteringNetworkServices registers a new resource with the given unique name, arguments, and options.
func NewFirewallFilteringNetworkServices(ctx *pulumi.Context,
	name string, args *FirewallFilteringNetworkServicesArgs, opts ...pulumi.ResourceOption) (*FirewallFilteringNetworkServices, error) {
	if args == nil {
		args = &FirewallFilteringNetworkServicesArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource FirewallFilteringNetworkServices
	err := ctx.RegisterResource("zia:index/firewallFilteringNetworkServices:FirewallFilteringNetworkServices", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFirewallFilteringNetworkServices gets an existing FirewallFilteringNetworkServices resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFirewallFilteringNetworkServices(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FirewallFilteringNetworkServicesState, opts ...pulumi.ResourceOption) (*FirewallFilteringNetworkServices, error) {
	var resource FirewallFilteringNetworkServices
	err := ctx.ReadResource("zia:index/firewallFilteringNetworkServices:FirewallFilteringNetworkServices", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FirewallFilteringNetworkServices resources.
type firewallFilteringNetworkServicesState struct {
	Description *string `pulumi:"description"`
	// dest tcp ports
	DestTcpPorts []FirewallFilteringNetworkServicesDestTcpPort `pulumi:"destTcpPorts"`
	// dest udp ports
	DestUdpPorts     []FirewallFilteringNetworkServicesDestUdpPort `pulumi:"destUdpPorts"`
	IsNameL10nTag    *bool                                         `pulumi:"isNameL10nTag"`
	Name             *string                                       `pulumi:"name"`
	NetworkServiceId *int                                          `pulumi:"networkServiceId"`
	// src tcp ports
	SrcTcpPorts []FirewallFilteringNetworkServicesSrcTcpPort `pulumi:"srcTcpPorts"`
	// src udp ports
	SrcUdpPorts []FirewallFilteringNetworkServicesSrcUdpPort `pulumi:"srcUdpPorts"`
	Tag         *string                                      `pulumi:"tag"`
	Type        *string                                      `pulumi:"type"`
}

type FirewallFilteringNetworkServicesState struct {
	Description pulumi.StringPtrInput
	// dest tcp ports
	DestTcpPorts FirewallFilteringNetworkServicesDestTcpPortArrayInput
	// dest udp ports
	DestUdpPorts     FirewallFilteringNetworkServicesDestUdpPortArrayInput
	IsNameL10nTag    pulumi.BoolPtrInput
	Name             pulumi.StringPtrInput
	NetworkServiceId pulumi.IntPtrInput
	// src tcp ports
	SrcTcpPorts FirewallFilteringNetworkServicesSrcTcpPortArrayInput
	// src udp ports
	SrcUdpPorts FirewallFilteringNetworkServicesSrcUdpPortArrayInput
	Tag         pulumi.StringPtrInput
	Type        pulumi.StringPtrInput
}

func (FirewallFilteringNetworkServicesState) ElementType() reflect.Type {
	return reflect.TypeOf((*firewallFilteringNetworkServicesState)(nil)).Elem()
}

type firewallFilteringNetworkServicesArgs struct {
	Description *string `pulumi:"description"`
	// dest tcp ports
	DestTcpPorts []FirewallFilteringNetworkServicesDestTcpPort `pulumi:"destTcpPorts"`
	// dest udp ports
	DestUdpPorts  []FirewallFilteringNetworkServicesDestUdpPort `pulumi:"destUdpPorts"`
	IsNameL10nTag *bool                                         `pulumi:"isNameL10nTag"`
	Name          *string                                       `pulumi:"name"`
	// src tcp ports
	SrcTcpPorts []FirewallFilteringNetworkServicesSrcTcpPort `pulumi:"srcTcpPorts"`
	// src udp ports
	SrcUdpPorts []FirewallFilteringNetworkServicesSrcUdpPort `pulumi:"srcUdpPorts"`
	Tag         *string                                      `pulumi:"tag"`
	Type        *string                                      `pulumi:"type"`
}

// The set of arguments for constructing a FirewallFilteringNetworkServices resource.
type FirewallFilteringNetworkServicesArgs struct {
	Description pulumi.StringPtrInput
	// dest tcp ports
	DestTcpPorts FirewallFilteringNetworkServicesDestTcpPortArrayInput
	// dest udp ports
	DestUdpPorts  FirewallFilteringNetworkServicesDestUdpPortArrayInput
	IsNameL10nTag pulumi.BoolPtrInput
	Name          pulumi.StringPtrInput
	// src tcp ports
	SrcTcpPorts FirewallFilteringNetworkServicesSrcTcpPortArrayInput
	// src udp ports
	SrcUdpPorts FirewallFilteringNetworkServicesSrcUdpPortArrayInput
	Tag         pulumi.StringPtrInput
	Type        pulumi.StringPtrInput
}

func (FirewallFilteringNetworkServicesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*firewallFilteringNetworkServicesArgs)(nil)).Elem()
}

type FirewallFilteringNetworkServicesInput interface {
	pulumi.Input

	ToFirewallFilteringNetworkServicesOutput() FirewallFilteringNetworkServicesOutput
	ToFirewallFilteringNetworkServicesOutputWithContext(ctx context.Context) FirewallFilteringNetworkServicesOutput
}

func (*FirewallFilteringNetworkServices) ElementType() reflect.Type {
	return reflect.TypeOf((**FirewallFilteringNetworkServices)(nil)).Elem()
}

func (i *FirewallFilteringNetworkServices) ToFirewallFilteringNetworkServicesOutput() FirewallFilteringNetworkServicesOutput {
	return i.ToFirewallFilteringNetworkServicesOutputWithContext(context.Background())
}

func (i *FirewallFilteringNetworkServices) ToFirewallFilteringNetworkServicesOutputWithContext(ctx context.Context) FirewallFilteringNetworkServicesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FirewallFilteringNetworkServicesOutput)
}

// FirewallFilteringNetworkServicesArrayInput is an input type that accepts FirewallFilteringNetworkServicesArray and FirewallFilteringNetworkServicesArrayOutput values.
// You can construct a concrete instance of `FirewallFilteringNetworkServicesArrayInput` via:
//
//	FirewallFilteringNetworkServicesArray{ FirewallFilteringNetworkServicesArgs{...} }
type FirewallFilteringNetworkServicesArrayInput interface {
	pulumi.Input

	ToFirewallFilteringNetworkServicesArrayOutput() FirewallFilteringNetworkServicesArrayOutput
	ToFirewallFilteringNetworkServicesArrayOutputWithContext(context.Context) FirewallFilteringNetworkServicesArrayOutput
}

type FirewallFilteringNetworkServicesArray []FirewallFilteringNetworkServicesInput

func (FirewallFilteringNetworkServicesArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FirewallFilteringNetworkServices)(nil)).Elem()
}

func (i FirewallFilteringNetworkServicesArray) ToFirewallFilteringNetworkServicesArrayOutput() FirewallFilteringNetworkServicesArrayOutput {
	return i.ToFirewallFilteringNetworkServicesArrayOutputWithContext(context.Background())
}

func (i FirewallFilteringNetworkServicesArray) ToFirewallFilteringNetworkServicesArrayOutputWithContext(ctx context.Context) FirewallFilteringNetworkServicesArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FirewallFilteringNetworkServicesArrayOutput)
}

// FirewallFilteringNetworkServicesMapInput is an input type that accepts FirewallFilteringNetworkServicesMap and FirewallFilteringNetworkServicesMapOutput values.
// You can construct a concrete instance of `FirewallFilteringNetworkServicesMapInput` via:
//
//	FirewallFilteringNetworkServicesMap{ "key": FirewallFilteringNetworkServicesArgs{...} }
type FirewallFilteringNetworkServicesMapInput interface {
	pulumi.Input

	ToFirewallFilteringNetworkServicesMapOutput() FirewallFilteringNetworkServicesMapOutput
	ToFirewallFilteringNetworkServicesMapOutputWithContext(context.Context) FirewallFilteringNetworkServicesMapOutput
}

type FirewallFilteringNetworkServicesMap map[string]FirewallFilteringNetworkServicesInput

func (FirewallFilteringNetworkServicesMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FirewallFilteringNetworkServices)(nil)).Elem()
}

func (i FirewallFilteringNetworkServicesMap) ToFirewallFilteringNetworkServicesMapOutput() FirewallFilteringNetworkServicesMapOutput {
	return i.ToFirewallFilteringNetworkServicesMapOutputWithContext(context.Background())
}

func (i FirewallFilteringNetworkServicesMap) ToFirewallFilteringNetworkServicesMapOutputWithContext(ctx context.Context) FirewallFilteringNetworkServicesMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FirewallFilteringNetworkServicesMapOutput)
}

type FirewallFilteringNetworkServicesOutput struct{ *pulumi.OutputState }

func (FirewallFilteringNetworkServicesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FirewallFilteringNetworkServices)(nil)).Elem()
}

func (o FirewallFilteringNetworkServicesOutput) ToFirewallFilteringNetworkServicesOutput() FirewallFilteringNetworkServicesOutput {
	return o
}

func (o FirewallFilteringNetworkServicesOutput) ToFirewallFilteringNetworkServicesOutputWithContext(ctx context.Context) FirewallFilteringNetworkServicesOutput {
	return o
}

func (o FirewallFilteringNetworkServicesOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FirewallFilteringNetworkServices) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// dest tcp ports
func (o FirewallFilteringNetworkServicesOutput) DestTcpPorts() FirewallFilteringNetworkServicesDestTcpPortArrayOutput {
	return o.ApplyT(func(v *FirewallFilteringNetworkServices) FirewallFilteringNetworkServicesDestTcpPortArrayOutput {
		return v.DestTcpPorts
	}).(FirewallFilteringNetworkServicesDestTcpPortArrayOutput)
}

// dest udp ports
func (o FirewallFilteringNetworkServicesOutput) DestUdpPorts() FirewallFilteringNetworkServicesDestUdpPortArrayOutput {
	return o.ApplyT(func(v *FirewallFilteringNetworkServices) FirewallFilteringNetworkServicesDestUdpPortArrayOutput {
		return v.DestUdpPorts
	}).(FirewallFilteringNetworkServicesDestUdpPortArrayOutput)
}

func (o FirewallFilteringNetworkServicesOutput) IsNameL10nTag() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *FirewallFilteringNetworkServices) pulumi.BoolPtrOutput { return v.IsNameL10nTag }).(pulumi.BoolPtrOutput)
}

func (o FirewallFilteringNetworkServicesOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallFilteringNetworkServices) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o FirewallFilteringNetworkServicesOutput) NetworkServiceId() pulumi.IntOutput {
	return o.ApplyT(func(v *FirewallFilteringNetworkServices) pulumi.IntOutput { return v.NetworkServiceId }).(pulumi.IntOutput)
}

// src tcp ports
func (o FirewallFilteringNetworkServicesOutput) SrcTcpPorts() FirewallFilteringNetworkServicesSrcTcpPortArrayOutput {
	return o.ApplyT(func(v *FirewallFilteringNetworkServices) FirewallFilteringNetworkServicesSrcTcpPortArrayOutput {
		return v.SrcTcpPorts
	}).(FirewallFilteringNetworkServicesSrcTcpPortArrayOutput)
}

// src udp ports
func (o FirewallFilteringNetworkServicesOutput) SrcUdpPorts() FirewallFilteringNetworkServicesSrcUdpPortArrayOutput {
	return o.ApplyT(func(v *FirewallFilteringNetworkServices) FirewallFilteringNetworkServicesSrcUdpPortArrayOutput {
		return v.SrcUdpPorts
	}).(FirewallFilteringNetworkServicesSrcUdpPortArrayOutput)
}

func (o FirewallFilteringNetworkServicesOutput) Tag() pulumi.StringOutput {
	return o.ApplyT(func(v *FirewallFilteringNetworkServices) pulumi.StringOutput { return v.Tag }).(pulumi.StringOutput)
}

func (o FirewallFilteringNetworkServicesOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FirewallFilteringNetworkServices) pulumi.StringPtrOutput { return v.Type }).(pulumi.StringPtrOutput)
}

type FirewallFilteringNetworkServicesArrayOutput struct{ *pulumi.OutputState }

func (FirewallFilteringNetworkServicesArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FirewallFilteringNetworkServices)(nil)).Elem()
}

func (o FirewallFilteringNetworkServicesArrayOutput) ToFirewallFilteringNetworkServicesArrayOutput() FirewallFilteringNetworkServicesArrayOutput {
	return o
}

func (o FirewallFilteringNetworkServicesArrayOutput) ToFirewallFilteringNetworkServicesArrayOutputWithContext(ctx context.Context) FirewallFilteringNetworkServicesArrayOutput {
	return o
}

func (o FirewallFilteringNetworkServicesArrayOutput) Index(i pulumi.IntInput) FirewallFilteringNetworkServicesOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FirewallFilteringNetworkServices {
		return vs[0].([]*FirewallFilteringNetworkServices)[vs[1].(int)]
	}).(FirewallFilteringNetworkServicesOutput)
}

type FirewallFilteringNetworkServicesMapOutput struct{ *pulumi.OutputState }

func (FirewallFilteringNetworkServicesMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FirewallFilteringNetworkServices)(nil)).Elem()
}

func (o FirewallFilteringNetworkServicesMapOutput) ToFirewallFilteringNetworkServicesMapOutput() FirewallFilteringNetworkServicesMapOutput {
	return o
}

func (o FirewallFilteringNetworkServicesMapOutput) ToFirewallFilteringNetworkServicesMapOutputWithContext(ctx context.Context) FirewallFilteringNetworkServicesMapOutput {
	return o
}

func (o FirewallFilteringNetworkServicesMapOutput) MapIndex(k pulumi.StringInput) FirewallFilteringNetworkServicesOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FirewallFilteringNetworkServices {
		return vs[0].(map[string]*FirewallFilteringNetworkServices)[vs[1].(string)]
	}).(FirewallFilteringNetworkServicesOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FirewallFilteringNetworkServicesInput)(nil)).Elem(), &FirewallFilteringNetworkServices{})
	pulumi.RegisterInputType(reflect.TypeOf((*FirewallFilteringNetworkServicesArrayInput)(nil)).Elem(), FirewallFilteringNetworkServicesArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FirewallFilteringNetworkServicesMapInput)(nil)).Elem(), FirewallFilteringNetworkServicesMap{})
	pulumi.RegisterOutputType(FirewallFilteringNetworkServicesOutput{})
	pulumi.RegisterOutputType(FirewallFilteringNetworkServicesArrayOutput{})
	pulumi.RegisterOutputType(FirewallFilteringNetworkServicesMapOutput{})
}
