// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zia

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/zscaler/pulumi-zia/sdk/go/zia/internal"
)

// Use the **zia_firewall_filtering_application_services_group** data source to get information about a network application group available in the Zscaler Internet Access cloud firewall. This data source can then be associated with a ZIA firewall filtering network application rule.
//
// ## Example Usage
//
// Deprecated: zia.index/getfirewallfilteringappgroups.getFirewallFilteringAppGroups has been deprecated in favor of zia.index/getfirewallfilteringappgroup.getFirewallFilteringAppGroup
func GetFirewallFilteringAppGroups(ctx *pulumi.Context, args *GetFirewallFilteringAppGroupsArgs, opts ...pulumi.InvokeOption) (*GetFirewallFilteringAppGroupsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetFirewallFilteringAppGroupsResult
	err := ctx.Invoke("zia:index/getFirewallFilteringAppGroups:getFirewallFilteringAppGroups", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFirewallFilteringAppGroups.
type GetFirewallFilteringAppGroupsArgs struct {
	// The name of the ip source group to be exported.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getFirewallFilteringAppGroups.
type GetFirewallFilteringAppGroupsResult struct {
	// The ID of this resource.
	Id          int    `pulumi:"id"`
	Name        string `pulumi:"name"`
	NameL10nTag bool   `pulumi:"nameL10nTag"`
}

func GetFirewallFilteringAppGroupsOutput(ctx *pulumi.Context, args GetFirewallFilteringAppGroupsOutputArgs, opts ...pulumi.InvokeOption) GetFirewallFilteringAppGroupsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetFirewallFilteringAppGroupsResultOutput, error) {
			args := v.(GetFirewallFilteringAppGroupsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("zia:index/getFirewallFilteringAppGroups:getFirewallFilteringAppGroups", args, GetFirewallFilteringAppGroupsResultOutput{}, options).(GetFirewallFilteringAppGroupsResultOutput), nil
		}).(GetFirewallFilteringAppGroupsResultOutput)
}

// A collection of arguments for invoking getFirewallFilteringAppGroups.
type GetFirewallFilteringAppGroupsOutputArgs struct {
	// The name of the ip source group to be exported.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (GetFirewallFilteringAppGroupsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFirewallFilteringAppGroupsArgs)(nil)).Elem()
}

// A collection of values returned by getFirewallFilteringAppGroups.
type GetFirewallFilteringAppGroupsResultOutput struct{ *pulumi.OutputState }

func (GetFirewallFilteringAppGroupsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFirewallFilteringAppGroupsResult)(nil)).Elem()
}

func (o GetFirewallFilteringAppGroupsResultOutput) ToGetFirewallFilteringAppGroupsResultOutput() GetFirewallFilteringAppGroupsResultOutput {
	return o
}

func (o GetFirewallFilteringAppGroupsResultOutput) ToGetFirewallFilteringAppGroupsResultOutputWithContext(ctx context.Context) GetFirewallFilteringAppGroupsResultOutput {
	return o
}

// The ID of this resource.
func (o GetFirewallFilteringAppGroupsResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v GetFirewallFilteringAppGroupsResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o GetFirewallFilteringAppGroupsResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetFirewallFilteringAppGroupsResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetFirewallFilteringAppGroupsResultOutput) NameL10nTag() pulumi.BoolOutput {
	return o.ApplyT(func(v GetFirewallFilteringAppGroupsResult) bool { return v.NameL10nTag }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(GetFirewallFilteringAppGroupsResultOutput{})
}
