// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumizia

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/zscaler/pulumi-zia/sdk/go/pulumi-zia/internal"
)

// The zia.FtpControlPolicy resource manages the FTP control policy settings in the Zscaler Internet Access (ZIA) cloud.
// This is a singleton resource (one per tenant). The policy controls whether FTP and FTP-over-HTTP traffic is allowed
// or blocked, and which URLs and URL categories are subject to FTP controls. Deleting the Pulumi resource does not
// remove the underlying settings.
//
// ## Example Usage
//
// ## Import
//
// This is a singleton resource and import is not supported. The resource is managed by creating it in your Pulumi program.
type FtpControlPolicy struct {
	pulumi.CustomResourceState

	// Whether native FTP traffic is enabled.
	FtpEnabled pulumi.BoolPtrOutput `pulumi:"ftpEnabled"`
	// Whether FTP-over-HTTP traffic is enabled.
	FtpOverHttpEnabled pulumi.BoolPtrOutput `pulumi:"ftpOverHttpEnabled"`
	// List of URL categories subject to the FTP control policy.
	UrlCategories pulumi.StringArrayOutput `pulumi:"urlCategories"`
	// List of URLs subject to the FTP control policy.
	Urls pulumi.StringArrayOutput `pulumi:"urls"`
}

// NewFtpControlPolicy registers a new resource with the given unique name, arguments, and options.
func NewFtpControlPolicy(ctx *pulumi.Context,
	name string, args *FtpControlPolicyArgs, opts ...pulumi.ResourceOption) (*FtpControlPolicy, error) {
	if args == nil {
		args = &FtpControlPolicyArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource FtpControlPolicy
	err := ctx.RegisterResource("zia:index:FtpControlPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFtpControlPolicy gets an existing FtpControlPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFtpControlPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FtpControlPolicyState, opts ...pulumi.ResourceOption) (*FtpControlPolicy, error) {
	var resource FtpControlPolicy
	err := ctx.ReadResource("zia:index:FtpControlPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FtpControlPolicy resources.
type ftpControlPolicyState struct {
}

type FtpControlPolicyState struct {
}

func (FtpControlPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*ftpControlPolicyState)(nil)).Elem()
}

type ftpControlPolicyArgs struct {
	// Whether native FTP traffic is enabled.
	FtpEnabled *bool `pulumi:"ftpEnabled"`
	// Whether FTP-over-HTTP traffic is enabled.
	FtpOverHttpEnabled *bool `pulumi:"ftpOverHttpEnabled"`
	// List of URL categories subject to the FTP control policy.
	UrlCategories []string `pulumi:"urlCategories"`
	// List of URLs subject to the FTP control policy.
	Urls []string `pulumi:"urls"`
}

// The set of arguments for constructing a FtpControlPolicy resource.
type FtpControlPolicyArgs struct {
	// Whether native FTP traffic is enabled.
	FtpEnabled pulumi.BoolPtrInput
	// Whether FTP-over-HTTP traffic is enabled.
	FtpOverHttpEnabled pulumi.BoolPtrInput
	// List of URL categories subject to the FTP control policy.
	UrlCategories pulumi.StringArrayInput
	// List of URLs subject to the FTP control policy.
	Urls pulumi.StringArrayInput
}

func (FtpControlPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ftpControlPolicyArgs)(nil)).Elem()
}

type FtpControlPolicyInput interface {
	pulumi.Input

	ToFtpControlPolicyOutput() FtpControlPolicyOutput
	ToFtpControlPolicyOutputWithContext(ctx context.Context) FtpControlPolicyOutput
}

func (*FtpControlPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**FtpControlPolicy)(nil)).Elem()
}

func (i *FtpControlPolicy) ToFtpControlPolicyOutput() FtpControlPolicyOutput {
	return i.ToFtpControlPolicyOutputWithContext(context.Background())
}

func (i *FtpControlPolicy) ToFtpControlPolicyOutputWithContext(ctx context.Context) FtpControlPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FtpControlPolicyOutput)
}

// FtpControlPolicyArrayInput is an input type that accepts FtpControlPolicyArray and FtpControlPolicyArrayOutput values.
// You can construct a concrete instance of `FtpControlPolicyArrayInput` via:
//
//	FtpControlPolicyArray{ FtpControlPolicyArgs{...} }
type FtpControlPolicyArrayInput interface {
	pulumi.Input

	ToFtpControlPolicyArrayOutput() FtpControlPolicyArrayOutput
	ToFtpControlPolicyArrayOutputWithContext(context.Context) FtpControlPolicyArrayOutput
}

type FtpControlPolicyArray []FtpControlPolicyInput

func (FtpControlPolicyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FtpControlPolicy)(nil)).Elem()
}

func (i FtpControlPolicyArray) ToFtpControlPolicyArrayOutput() FtpControlPolicyArrayOutput {
	return i.ToFtpControlPolicyArrayOutputWithContext(context.Background())
}

func (i FtpControlPolicyArray) ToFtpControlPolicyArrayOutputWithContext(ctx context.Context) FtpControlPolicyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FtpControlPolicyArrayOutput)
}

// FtpControlPolicyMapInput is an input type that accepts FtpControlPolicyMap and FtpControlPolicyMapOutput values.
// You can construct a concrete instance of `FtpControlPolicyMapInput` via:
//
//	FtpControlPolicyMap{ "key": FtpControlPolicyArgs{...} }
type FtpControlPolicyMapInput interface {
	pulumi.Input

	ToFtpControlPolicyMapOutput() FtpControlPolicyMapOutput
	ToFtpControlPolicyMapOutputWithContext(context.Context) FtpControlPolicyMapOutput
}

type FtpControlPolicyMap map[string]FtpControlPolicyInput

func (FtpControlPolicyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FtpControlPolicy)(nil)).Elem()
}

func (i FtpControlPolicyMap) ToFtpControlPolicyMapOutput() FtpControlPolicyMapOutput {
	return i.ToFtpControlPolicyMapOutputWithContext(context.Background())
}

func (i FtpControlPolicyMap) ToFtpControlPolicyMapOutputWithContext(ctx context.Context) FtpControlPolicyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FtpControlPolicyMapOutput)
}

type FtpControlPolicyOutput struct{ *pulumi.OutputState }

func (FtpControlPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FtpControlPolicy)(nil)).Elem()
}

func (o FtpControlPolicyOutput) ToFtpControlPolicyOutput() FtpControlPolicyOutput {
	return o
}

func (o FtpControlPolicyOutput) ToFtpControlPolicyOutputWithContext(ctx context.Context) FtpControlPolicyOutput {
	return o
}

// Whether native FTP traffic is enabled.
func (o FtpControlPolicyOutput) FtpEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *FtpControlPolicy) pulumi.BoolPtrOutput { return v.FtpEnabled }).(pulumi.BoolPtrOutput)
}

// Whether FTP-over-HTTP traffic is enabled.
func (o FtpControlPolicyOutput) FtpOverHttpEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *FtpControlPolicy) pulumi.BoolPtrOutput { return v.FtpOverHttpEnabled }).(pulumi.BoolPtrOutput)
}

// List of URL categories subject to the FTP control policy.
func (o FtpControlPolicyOutput) UrlCategories() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *FtpControlPolicy) pulumi.StringArrayOutput { return v.UrlCategories }).(pulumi.StringArrayOutput)
}

// List of URLs subject to the FTP control policy.
func (o FtpControlPolicyOutput) Urls() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *FtpControlPolicy) pulumi.StringArrayOutput { return v.Urls }).(pulumi.StringArrayOutput)
}

type FtpControlPolicyArrayOutput struct{ *pulumi.OutputState }

func (FtpControlPolicyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FtpControlPolicy)(nil)).Elem()
}

func (o FtpControlPolicyArrayOutput) ToFtpControlPolicyArrayOutput() FtpControlPolicyArrayOutput {
	return o
}

func (o FtpControlPolicyArrayOutput) ToFtpControlPolicyArrayOutputWithContext(ctx context.Context) FtpControlPolicyArrayOutput {
	return o
}

func (o FtpControlPolicyArrayOutput) Index(i pulumi.IntInput) FtpControlPolicyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FtpControlPolicy {
		return vs[0].([]*FtpControlPolicy)[vs[1].(int)]
	}).(FtpControlPolicyOutput)
}

type FtpControlPolicyMapOutput struct{ *pulumi.OutputState }

func (FtpControlPolicyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FtpControlPolicy)(nil)).Elem()
}

func (o FtpControlPolicyMapOutput) ToFtpControlPolicyMapOutput() FtpControlPolicyMapOutput {
	return o
}

func (o FtpControlPolicyMapOutput) ToFtpControlPolicyMapOutputWithContext(ctx context.Context) FtpControlPolicyMapOutput {
	return o
}

func (o FtpControlPolicyMapOutput) MapIndex(k pulumi.StringInput) FtpControlPolicyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FtpControlPolicy {
		return vs[0].(map[string]*FtpControlPolicy)[vs[1].(string)]
	}).(FtpControlPolicyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FtpControlPolicyInput)(nil)).Elem(), &FtpControlPolicy{})
	pulumi.RegisterInputType(reflect.TypeOf((*FtpControlPolicyArrayInput)(nil)).Elem(), FtpControlPolicyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FtpControlPolicyMapInput)(nil)).Elem(), FtpControlPolicyMap{})
	pulumi.RegisterOutputType(FtpControlPolicyOutput{})
	pulumi.RegisterOutputType(FtpControlPolicyArrayOutput{})
	pulumi.RegisterOutputType(FtpControlPolicyMapOutput{})
}
