// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumizia

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/zscaler/pulumi-zia/sdk/go/pulumi-zia/internal"
)

// The zia_fw_network_service resource manages firewall network services in the Zscaler Internet Access (ZIA) cloud service. Network services define the TCP/UDP port ranges used in firewall filtering rules.
//
// For more information, see the [ZIA Firewall Policies documentation](https://help.zscaler.com/zia/firewall-policies).
//
// ## Example Usage
//
// ## Import
//
// An existing network service can be imported using its resource ID, e.g.
//
// ```sh
// $ pulumi import zia:index:FwNetworkService example 12345
// ```
type FwNetworkService struct {
	pulumi.CustomResourceState

	// Additional information about the network service.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Destination TCP port ranges. Each entry specifies a start and end port.
	DestTcpPorts NetworkPortInputArrayOutput `pulumi:"destTcpPorts"`
	// Destination UDP port ranges. Each entry specifies a start and end port.
	DestUdpPorts NetworkPortInputArrayOutput `pulumi:"destUdpPorts"`
	// Indicates whether the name is a localization tag.
	IsNameL10nTag pulumi.BoolPtrOutput `pulumi:"isNameL10nTag"`
	// The name of the network service.
	Name pulumi.StringPtrOutput `pulumi:"name"`
	// The system-generated ID of the network service.
	NetworkServiceId pulumi.IntOutput `pulumi:"networkServiceId"`
	// Source TCP port ranges. Each entry specifies a start and end port.
	SrcTcpPorts NetworkPortInputArrayOutput `pulumi:"srcTcpPorts"`
	// Source UDP port ranges. Each entry specifies a start and end port.
	SrcUdpPorts NetworkPortInputArrayOutput `pulumi:"srcUdpPorts"`
	// The tag associated with the network service.
	Tag pulumi.StringPtrOutput `pulumi:"tag"`
	// The network service type. Valid values: `STANDARD`, `PREDEFINED`, `CUSTOM`.
	Type pulumi.StringPtrOutput `pulumi:"type"`
}

// NewFwNetworkService registers a new resource with the given unique name, arguments, and options.
func NewFwNetworkService(ctx *pulumi.Context,
	name string, args *FwNetworkServiceArgs, opts ...pulumi.ResourceOption) (*FwNetworkService, error) {
	if args == nil {
		args = &FwNetworkServiceArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource FwNetworkService
	err := ctx.RegisterResource("zia:index:FwNetworkService", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFwNetworkService gets an existing FwNetworkService resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFwNetworkService(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FwNetworkServiceState, opts ...pulumi.ResourceOption) (*FwNetworkService, error) {
	var resource FwNetworkService
	err := ctx.ReadResource("zia:index:FwNetworkService", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FwNetworkService resources.
type fwNetworkServiceState struct {
}

type FwNetworkServiceState struct {
}

func (FwNetworkServiceState) ElementType() reflect.Type {
	return reflect.TypeOf((*fwNetworkServiceState)(nil)).Elem()
}

type fwNetworkServiceArgs struct {
	// Additional information about the network service.
	Description *string `pulumi:"description"`
	// Destination TCP port ranges. Each entry specifies a start and end port.
	DestTcpPorts []NetworkPortInput `pulumi:"destTcpPorts"`
	// Destination UDP port ranges. Each entry specifies a start and end port.
	DestUdpPorts []NetworkPortInput `pulumi:"destUdpPorts"`
	// Indicates whether the name is a localization tag.
	IsNameL10nTag *bool `pulumi:"isNameL10nTag"`
	// The name of the network service.
	Name *string `pulumi:"name"`
	// Source TCP port ranges. Each entry specifies a start and end port.
	SrcTcpPorts []NetworkPortInput `pulumi:"srcTcpPorts"`
	// Source UDP port ranges. Each entry specifies a start and end port.
	SrcUdpPorts []NetworkPortInput `pulumi:"srcUdpPorts"`
	// The tag associated with the network service.
	Tag *string `pulumi:"tag"`
	// The network service type. Valid values: `STANDARD`, `PREDEFINED`, `CUSTOM`.
	Type *string `pulumi:"type"`
}

// The set of arguments for constructing a FwNetworkService resource.
type FwNetworkServiceArgs struct {
	// Additional information about the network service.
	Description pulumi.StringPtrInput
	// Destination TCP port ranges. Each entry specifies a start and end port.
	DestTcpPorts NetworkPortInputArrayInput
	// Destination UDP port ranges. Each entry specifies a start and end port.
	DestUdpPorts NetworkPortInputArrayInput
	// Indicates whether the name is a localization tag.
	IsNameL10nTag pulumi.BoolPtrInput
	// The name of the network service.
	Name pulumi.StringPtrInput
	// Source TCP port ranges. Each entry specifies a start and end port.
	SrcTcpPorts NetworkPortInputArrayInput
	// Source UDP port ranges. Each entry specifies a start and end port.
	SrcUdpPorts NetworkPortInputArrayInput
	// The tag associated with the network service.
	Tag pulumi.StringPtrInput
	// The network service type. Valid values: `STANDARD`, `PREDEFINED`, `CUSTOM`.
	Type pulumi.StringPtrInput
}

func (FwNetworkServiceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*fwNetworkServiceArgs)(nil)).Elem()
}

type FwNetworkServiceInput interface {
	pulumi.Input

	ToFwNetworkServiceOutput() FwNetworkServiceOutput
	ToFwNetworkServiceOutputWithContext(ctx context.Context) FwNetworkServiceOutput
}

func (*FwNetworkService) ElementType() reflect.Type {
	return reflect.TypeOf((**FwNetworkService)(nil)).Elem()
}

func (i *FwNetworkService) ToFwNetworkServiceOutput() FwNetworkServiceOutput {
	return i.ToFwNetworkServiceOutputWithContext(context.Background())
}

func (i *FwNetworkService) ToFwNetworkServiceOutputWithContext(ctx context.Context) FwNetworkServiceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FwNetworkServiceOutput)
}

// FwNetworkServiceArrayInput is an input type that accepts FwNetworkServiceArray and FwNetworkServiceArrayOutput values.
// You can construct a concrete instance of `FwNetworkServiceArrayInput` via:
//
//	FwNetworkServiceArray{ FwNetworkServiceArgs{...} }
type FwNetworkServiceArrayInput interface {
	pulumi.Input

	ToFwNetworkServiceArrayOutput() FwNetworkServiceArrayOutput
	ToFwNetworkServiceArrayOutputWithContext(context.Context) FwNetworkServiceArrayOutput
}

type FwNetworkServiceArray []FwNetworkServiceInput

func (FwNetworkServiceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FwNetworkService)(nil)).Elem()
}

func (i FwNetworkServiceArray) ToFwNetworkServiceArrayOutput() FwNetworkServiceArrayOutput {
	return i.ToFwNetworkServiceArrayOutputWithContext(context.Background())
}

func (i FwNetworkServiceArray) ToFwNetworkServiceArrayOutputWithContext(ctx context.Context) FwNetworkServiceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FwNetworkServiceArrayOutput)
}

// FwNetworkServiceMapInput is an input type that accepts FwNetworkServiceMap and FwNetworkServiceMapOutput values.
// You can construct a concrete instance of `FwNetworkServiceMapInput` via:
//
//	FwNetworkServiceMap{ "key": FwNetworkServiceArgs{...} }
type FwNetworkServiceMapInput interface {
	pulumi.Input

	ToFwNetworkServiceMapOutput() FwNetworkServiceMapOutput
	ToFwNetworkServiceMapOutputWithContext(context.Context) FwNetworkServiceMapOutput
}

type FwNetworkServiceMap map[string]FwNetworkServiceInput

func (FwNetworkServiceMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FwNetworkService)(nil)).Elem()
}

func (i FwNetworkServiceMap) ToFwNetworkServiceMapOutput() FwNetworkServiceMapOutput {
	return i.ToFwNetworkServiceMapOutputWithContext(context.Background())
}

func (i FwNetworkServiceMap) ToFwNetworkServiceMapOutputWithContext(ctx context.Context) FwNetworkServiceMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FwNetworkServiceMapOutput)
}

type FwNetworkServiceOutput struct{ *pulumi.OutputState }

func (FwNetworkServiceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FwNetworkService)(nil)).Elem()
}

func (o FwNetworkServiceOutput) ToFwNetworkServiceOutput() FwNetworkServiceOutput {
	return o
}

func (o FwNetworkServiceOutput) ToFwNetworkServiceOutputWithContext(ctx context.Context) FwNetworkServiceOutput {
	return o
}

// Additional information about the network service.
func (o FwNetworkServiceOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FwNetworkService) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Destination TCP port ranges. Each entry specifies a start and end port.
func (o FwNetworkServiceOutput) DestTcpPorts() NetworkPortInputArrayOutput {
	return o.ApplyT(func(v *FwNetworkService) NetworkPortInputArrayOutput { return v.DestTcpPorts }).(NetworkPortInputArrayOutput)
}

// Destination UDP port ranges. Each entry specifies a start and end port.
func (o FwNetworkServiceOutput) DestUdpPorts() NetworkPortInputArrayOutput {
	return o.ApplyT(func(v *FwNetworkService) NetworkPortInputArrayOutput { return v.DestUdpPorts }).(NetworkPortInputArrayOutput)
}

// Indicates whether the name is a localization tag.
func (o FwNetworkServiceOutput) IsNameL10nTag() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *FwNetworkService) pulumi.BoolPtrOutput { return v.IsNameL10nTag }).(pulumi.BoolPtrOutput)
}

// The name of the network service.
func (o FwNetworkServiceOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FwNetworkService) pulumi.StringPtrOutput { return v.Name }).(pulumi.StringPtrOutput)
}

// The system-generated ID of the network service.
func (o FwNetworkServiceOutput) NetworkServiceId() pulumi.IntOutput {
	return o.ApplyT(func(v *FwNetworkService) pulumi.IntOutput { return v.NetworkServiceId }).(pulumi.IntOutput)
}

// Source TCP port ranges. Each entry specifies a start and end port.
func (o FwNetworkServiceOutput) SrcTcpPorts() NetworkPortInputArrayOutput {
	return o.ApplyT(func(v *FwNetworkService) NetworkPortInputArrayOutput { return v.SrcTcpPorts }).(NetworkPortInputArrayOutput)
}

// Source UDP port ranges. Each entry specifies a start and end port.
func (o FwNetworkServiceOutput) SrcUdpPorts() NetworkPortInputArrayOutput {
	return o.ApplyT(func(v *FwNetworkService) NetworkPortInputArrayOutput { return v.SrcUdpPorts }).(NetworkPortInputArrayOutput)
}

// The tag associated with the network service.
func (o FwNetworkServiceOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FwNetworkService) pulumi.StringPtrOutput { return v.Tag }).(pulumi.StringPtrOutput)
}

// The network service type. Valid values: `STANDARD`, `PREDEFINED`, `CUSTOM`.
func (o FwNetworkServiceOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FwNetworkService) pulumi.StringPtrOutput { return v.Type }).(pulumi.StringPtrOutput)
}

type FwNetworkServiceArrayOutput struct{ *pulumi.OutputState }

func (FwNetworkServiceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FwNetworkService)(nil)).Elem()
}

func (o FwNetworkServiceArrayOutput) ToFwNetworkServiceArrayOutput() FwNetworkServiceArrayOutput {
	return o
}

func (o FwNetworkServiceArrayOutput) ToFwNetworkServiceArrayOutputWithContext(ctx context.Context) FwNetworkServiceArrayOutput {
	return o
}

func (o FwNetworkServiceArrayOutput) Index(i pulumi.IntInput) FwNetworkServiceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FwNetworkService {
		return vs[0].([]*FwNetworkService)[vs[1].(int)]
	}).(FwNetworkServiceOutput)
}

type FwNetworkServiceMapOutput struct{ *pulumi.OutputState }

func (FwNetworkServiceMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FwNetworkService)(nil)).Elem()
}

func (o FwNetworkServiceMapOutput) ToFwNetworkServiceMapOutput() FwNetworkServiceMapOutput {
	return o
}

func (o FwNetworkServiceMapOutput) ToFwNetworkServiceMapOutputWithContext(ctx context.Context) FwNetworkServiceMapOutput {
	return o
}

func (o FwNetworkServiceMapOutput) MapIndex(k pulumi.StringInput) FwNetworkServiceOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FwNetworkService {
		return vs[0].(map[string]*FwNetworkService)[vs[1].(string)]
	}).(FwNetworkServiceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FwNetworkServiceInput)(nil)).Elem(), &FwNetworkService{})
	pulumi.RegisterInputType(reflect.TypeOf((*FwNetworkServiceArrayInput)(nil)).Elem(), FwNetworkServiceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FwNetworkServiceMapInput)(nil)).Elem(), FwNetworkServiceMap{})
	pulumi.RegisterOutputType(FwNetworkServiceOutput{})
	pulumi.RegisterOutputType(FwNetworkServiceArrayOutput{})
	pulumi.RegisterOutputType(FwNetworkServiceMapOutput{})
}
