// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumizia

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/zscaler/pulumi-zia/sdk/go/pulumi-zia/internal"
)

// Use the **zia:index/getDatacenters:getDatacenters** data source to retrieve a list of Zscaler data centers. Results can be filtered by datacenter ID, name (case-insensitive partial match), or city (case-insensitive partial match).
//
// ## Example Usage
// ### Retrieve All Datacenters
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/zscaler/pulumi-zia/sdk/go/pulumi-zia"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			all, err := zia.GetDatacenters(ctx, &zia.GetDatacentersArgs{}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("datacenters", pulumi.ToStringArray(all.Datacenters))
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// This data source is read-only and does not support import.
func GetDatacenters(ctx *pulumi.Context, args *GetDatacentersArgs, opts ...pulumi.InvokeOption) (*GetDatacentersResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDatacentersResult
	err := ctx.Invoke("zia:index:getDatacenters", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetDatacentersArgs struct {
	// Filter datacenters by city (case-insensitive partial match). When exactly one result is returned, this is set to that datacenter's city.
	City *string `pulumi:"city"`
	// Filter datacenters by ID. When exactly one result is returned, this is set to that datacenter's ID.
	DatacenterId *int `pulumi:"datacenterId"`
	// Filter datacenters by name (case-insensitive partial match). When exactly one result is returned, this is set to that datacenter's name.
	Name *string `pulumi:"name"`
}

type GetDatacentersResult struct {
	// The datacenter city when exactly one result is returned.
	City *string `pulumi:"city"`
	// The datacenter ID when exactly one result is returned.
	DatacenterId *int `pulumi:"datacenterId"`
	// List of datacenters matching the filter criteria.
	Datacenters []DatacenterInfo `pulumi:"datacenters"`
	// The datacenter name when exactly one result is returned.
	Name *string `pulumi:"name"`
}

func GetDatacentersOutput(ctx *pulumi.Context, args GetDatacentersOutputArgs, opts ...pulumi.InvokeOption) GetDatacentersResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetDatacentersResultOutput, error) {
			args := v.(GetDatacentersArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("zia:index:getDatacenters", args, GetDatacentersResultOutput{}, options).(GetDatacentersResultOutput), nil
		}).(GetDatacentersResultOutput)
}

type GetDatacentersOutputArgs struct {
	// Filter datacenters by city (case-insensitive partial match). When exactly one result is returned, this is set to that datacenter's city.
	City pulumi.StringPtrInput `pulumi:"city"`
	// Filter datacenters by ID. When exactly one result is returned, this is set to that datacenter's ID.
	DatacenterId pulumi.IntPtrInput `pulumi:"datacenterId"`
	// Filter datacenters by name (case-insensitive partial match). When exactly one result is returned, this is set to that datacenter's name.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (GetDatacentersOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDatacentersArgs)(nil)).Elem()
}

type GetDatacentersResultOutput struct{ *pulumi.OutputState }

func (GetDatacentersResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDatacentersResult)(nil)).Elem()
}

func (o GetDatacentersResultOutput) ToGetDatacentersResultOutput() GetDatacentersResultOutput {
	return o
}

func (o GetDatacentersResultOutput) ToGetDatacentersResultOutputWithContext(ctx context.Context) GetDatacentersResultOutput {
	return o
}

// The datacenter city when exactly one result is returned.
func (o GetDatacentersResultOutput) City() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetDatacentersResult) *string { return v.City }).(pulumi.StringPtrOutput)
}

// The datacenter ID when exactly one result is returned.
func (o GetDatacentersResultOutput) DatacenterId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetDatacentersResult) *int { return v.DatacenterId }).(pulumi.IntPtrOutput)
}

// List of datacenters matching the filter criteria.
func (o GetDatacentersResultOutput) Datacenters() DatacenterInfoArrayOutput {
	return o.ApplyT(func(v GetDatacentersResult) []DatacenterInfo { return v.Datacenters }).(DatacenterInfoArrayOutput)
}

// The datacenter name when exactly one result is returned.
func (o GetDatacentersResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetDatacentersResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDatacentersResultOutput{})
}
