// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.zia.zia.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetCloudBrowserIsolationProfilePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCloudBrowserIsolationProfilePlainArgs Empty = new GetCloudBrowserIsolationProfilePlainArgs();

    /**
     * The name of the cloud browser isolation profile to look up.
     * 
     */
    @Import(name="name")
    private @Nullable String name;

    /**
     * @return The name of the cloud browser isolation profile to look up.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    private GetCloudBrowserIsolationProfilePlainArgs() {}

    private GetCloudBrowserIsolationProfilePlainArgs(GetCloudBrowserIsolationProfilePlainArgs $) {
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCloudBrowserIsolationProfilePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCloudBrowserIsolationProfilePlainArgs $;

        public Builder() {
            $ = new GetCloudBrowserIsolationProfilePlainArgs();
        }

        public Builder(GetCloudBrowserIsolationProfilePlainArgs defaults) {
            $ = new GetCloudBrowserIsolationProfilePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the cloud browser isolation profile to look up.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable String name) {
            $.name = name;
            return this;
        }

        public GetCloudBrowserIsolationProfilePlainArgs build() {
            return $;
        }
    }

}
