// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.zia.zia.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetCasbTenantPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCasbTenantPlainArgs Empty = new GetCasbTenantPlainArgs();

    /**
     * If true, only return active tenants.
     * 
     */
    @Import(name="activeOnly")
    private @Nullable Boolean activeOnly;

    /**
     * @return If true, only return active tenants.
     * 
     */
    public Optional<Boolean> activeOnly() {
        return Optional.ofNullable(this.activeOnly);
    }

    /**
     * The application to filter by.
     * 
     */
    @Import(name="app")
    private @Nullable String app;

    /**
     * @return The application to filter by.
     * 
     */
    public Optional<String> app() {
        return Optional.ofNullable(this.app);
    }

    /**
     * The application type to filter by.
     * 
     */
    @Import(name="appType")
    private @Nullable String appType;

    /**
     * @return The application type to filter by.
     * 
     */
    public Optional<String> appType() {
        return Optional.ofNullable(this.appType);
    }

    /**
     * If true, include deleted tenants in the results.
     * 
     */
    @Import(name="includeDeleted")
    private @Nullable Boolean includeDeleted;

    /**
     * @return If true, include deleted tenants in the results.
     * 
     */
    public Optional<Boolean> includeDeleted() {
        return Optional.ofNullable(this.includeDeleted);
    }

    /**
     * The ID of the CASB tenant to look up.
     * 
     */
    @Import(name="tenantId")
    private @Nullable Integer tenantId;

    /**
     * @return The ID of the CASB tenant to look up.
     * 
     */
    public Optional<Integer> tenantId() {
        return Optional.ofNullable(this.tenantId);
    }

    /**
     * The name of the CASB tenant to look up.
     * 
     */
    @Import(name="tenantName")
    private @Nullable String tenantName;

    /**
     * @return The name of the CASB tenant to look up.
     * 
     */
    public Optional<String> tenantName() {
        return Optional.ofNullable(this.tenantName);
    }

    private GetCasbTenantPlainArgs() {}

    private GetCasbTenantPlainArgs(GetCasbTenantPlainArgs $) {
        this.activeOnly = $.activeOnly;
        this.app = $.app;
        this.appType = $.appType;
        this.includeDeleted = $.includeDeleted;
        this.tenantId = $.tenantId;
        this.tenantName = $.tenantName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCasbTenantPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCasbTenantPlainArgs $;

        public Builder() {
            $ = new GetCasbTenantPlainArgs();
        }

        public Builder(GetCasbTenantPlainArgs defaults) {
            $ = new GetCasbTenantPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param activeOnly If true, only return active tenants.
         * 
         * @return builder
         * 
         */
        public Builder activeOnly(@Nullable Boolean activeOnly) {
            $.activeOnly = activeOnly;
            return this;
        }

        /**
         * @param app The application to filter by.
         * 
         * @return builder
         * 
         */
        public Builder app(@Nullable String app) {
            $.app = app;
            return this;
        }

        /**
         * @param appType The application type to filter by.
         * 
         * @return builder
         * 
         */
        public Builder appType(@Nullable String appType) {
            $.appType = appType;
            return this;
        }

        /**
         * @param includeDeleted If true, include deleted tenants in the results.
         * 
         * @return builder
         * 
         */
        public Builder includeDeleted(@Nullable Boolean includeDeleted) {
            $.includeDeleted = includeDeleted;
            return this;
        }

        /**
         * @param tenantId The ID of the CASB tenant to look up.
         * 
         * @return builder
         * 
         */
        public Builder tenantId(@Nullable Integer tenantId) {
            $.tenantId = tenantId;
            return this;
        }

        /**
         * @param tenantName The name of the CASB tenant to look up.
         * 
         * @return builder
         * 
         */
        public Builder tenantName(@Nullable String tenantName) {
            $.tenantName = tenantName;
            return this;
        }

        public GetCasbTenantPlainArgs build() {
            return $;
        }
    }

}
