// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.zia.zia.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetDlpIcapServerPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetDlpIcapServerPlainArgs Empty = new GetDlpIcapServerPlainArgs();

    /**
     * The name of the DLP ICAP server to look up.
     * 
     */
    @Import(name="name")
    private @Nullable String name;

    /**
     * @return The name of the DLP ICAP server to look up.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The ID of the DLP ICAP server to look up.
     * 
     */
    @Import(name="resourceId")
    private @Nullable Integer resourceId;

    /**
     * @return The ID of the DLP ICAP server to look up.
     * 
     */
    public Optional<Integer> resourceId() {
        return Optional.ofNullable(this.resourceId);
    }

    private GetDlpIcapServerPlainArgs() {}

    private GetDlpIcapServerPlainArgs(GetDlpIcapServerPlainArgs $) {
        this.name = $.name;
        this.resourceId = $.resourceId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDlpIcapServerPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDlpIcapServerPlainArgs $;

        public Builder() {
            $ = new GetDlpIcapServerPlainArgs();
        }

        public Builder(GetDlpIcapServerPlainArgs defaults) {
            $ = new GetDlpIcapServerPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the DLP ICAP server to look up.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable String name) {
            $.name = name;
            return this;
        }

        /**
         * @param resourceId The ID of the DLP ICAP server to look up.
         * 
         * @return builder
         * 
         */
        public Builder resourceId(@Nullable Integer resourceId) {
            $.resourceId = resourceId;
            return this;
        }

        public GetDlpIcapServerPlainArgs build() {
            return $;
        }
    }

}
