// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zia.Outputs
{

    [OutputType]
    public sealed class DLPDictionariesPhrase
    {
        public readonly string? Action;
        /// <summary>
        /// DLP dictionary phrase (0-128 characters)
        /// </summary>
        public readonly string? Phrase;

        [OutputConstructor]
        private DLPDictionariesPhrase(
            string? action,

            string? phrase)
        {
            Action = action;
            Phrase = phrase;
        }
    }
}
