// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zia.Outputs
{

    [OutputType]
    public sealed class GetForwardingControlProxiesCertResult
    {
        public readonly ImmutableDictionary<string, string> Extensions;
        /// <summary>
        /// The configured name of the entity
        /// </summary>
        public readonly string ExternalId;
        /// <summary>
        /// Unique identifier for the third-party proxy services
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Proxy name for the third-party proxy services
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetForwardingControlProxiesCertResult(
            ImmutableDictionary<string, string> extensions,

            string externalId,

            int id,

            string name)
        {
            Extensions = extensions;
            ExternalId = externalId;
            Id = id;
            Name = name;
        }
    }
}
