// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zia
{
    /// <summary>
    /// The zia_custom_file_type resource manages custom file type controls in the Zscaler Internet Access (ZIA) cloud service. Custom file types allow you to define file extensions and types for use in file type control policies.
    /// 
    /// ## Example Usage
    /// 
    /// ## Import
    /// 
    /// An existing Custom File Type can be imported using its resource ID, e.g.
    /// 
    /// ```sh
    /// $ pulumi import zia:index:CustomFileType example 12345
    /// ```
    /// </summary>
    [ZiaResourceType("zia:index:CustomFileType")]
    public partial class CustomFileType : global::Pulumi.CustomResource
    {
        /// <summary>
        /// A description of the custom file type.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The file extension for this custom file type (e.g. `myarch`).
        /// </summary>
        [Output("extension")]
        public Output<string?> Extension { get; private set; } = null!;

        /// <summary>
        /// The system-generated ID of the custom file type.
        /// </summary>
        [Output("fileId")]
        public Output<int> FileId { get; private set; } = null!;

        /// <summary>
        /// The file type category ID to associate this custom file type with.
        /// </summary>
        [Output("fileTypeId")]
        public Output<int?> FileTypeId { get; private set; } = null!;

        /// <summary>
        /// The name of the custom file type.
        /// </summary>
        [Output("name")]
        public Output<string?> Name { get; private set; } = null!;


        /// <summary>
        /// Create a CustomFileType resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public CustomFileType(string name, CustomFileTypeArgs? args = null, CustomResourceOptions? options = null)
            : base("zia:index:CustomFileType", name, args ?? new CustomFileTypeArgs(), MakeResourceOptions(options, ""))
        {
        }

        private CustomFileType(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("zia:index:CustomFileType", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/zscaler",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing CustomFileType resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static CustomFileType Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new CustomFileType(name, id, options);
        }
    }

    public sealed class CustomFileTypeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A description of the custom file type.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The file extension for this custom file type (e.g. `myarch`).
        /// </summary>
        [Input("extension")]
        public Input<string>? Extension { get; set; }

        /// <summary>
        /// The file type category ID to associate this custom file type with.
        /// </summary>
        [Input("fileTypeId")]
        public Input<int>? FileTypeId { get; set; }

        /// <summary>
        /// The name of the custom file type.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public CustomFileTypeArgs()
        {
        }
        public static new CustomFileTypeArgs Empty => new CustomFileTypeArgs();
    }
}
