// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zia
{
    public static class GetCasbEmailLabel
    {
        /// <summary>
        /// Use this data source to look up a CASB email label by ID or name.
        /// </summary>
        public static Task<GetCasbEmailLabelResult> InvokeAsync(GetCasbEmailLabelArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCasbEmailLabelResult>("zia:index:getCasbEmailLabel", args ?? new GetCasbEmailLabelArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to look up a CASB email label by ID or name.
        /// </summary>
        public static Output<GetCasbEmailLabelResult> Invoke(GetCasbEmailLabelInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCasbEmailLabelResult>("zia:index:getCasbEmailLabel", args ?? new GetCasbEmailLabelInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to look up a CASB email label by ID or name.
        /// </summary>
        public static Output<GetCasbEmailLabelResult> Invoke(GetCasbEmailLabelInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetCasbEmailLabelResult>("zia:index:getCasbEmailLabel", args ?? new GetCasbEmailLabelInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCasbEmailLabelArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the CASB email label to look up.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// The ID of the CASB email label to look up.
        /// </summary>
        [Input("resourceId")]
        public int? ResourceId { get; set; }

        public GetCasbEmailLabelArgs()
        {
        }
        public static new GetCasbEmailLabelArgs Empty => new GetCasbEmailLabelArgs();
    }

    public sealed class GetCasbEmailLabelInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the CASB email label to look up.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The ID of the CASB email label to look up.
        /// </summary>
        [Input("resourceId")]
        public Input<int>? ResourceId { get; set; }

        public GetCasbEmailLabelInvokeArgs()
        {
        }
        public static new GetCasbEmailLabelInvokeArgs Empty => new GetCasbEmailLabelInvokeArgs();
    }


    [OutputType]
    public sealed class GetCasbEmailLabelResult
    {
        /// <summary>
        /// Whether the email label has been deleted.
        /// </summary>
        public readonly bool LabelDeleted;
        /// <summary>
        /// The name of the CASB email label.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The ID of the CASB email label.
        /// </summary>
        public readonly int ResourceId;

        [OutputConstructor]
        private GetCasbEmailLabelResult(
            bool labelDeleted,

            string name,

            int resourceId)
        {
            LabelDeleted = labelDeleted;
            Name = name;
            ResourceId = resourceId;
        }
    }
}
