// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zia
{
    [ZiaResourceType("zia:index:UrlCategory")]
    public partial class UrlCategory : global::Pulumi.CustomResource
    {
        [Output("categoryId")]
        public Output<string> CategoryId { get; private set; } = null!;

        [Output("configuredName")]
        public Output<string?> ConfiguredName { get; private set; } = null!;

        [Output("customCategory")]
        public Output<bool?> CustomCategory { get; private set; } = null!;

        [Output("customIpRangesCount")]
        public Output<int?> CustomIpRangesCount { get; private set; } = null!;

        [Output("customUrlsCount")]
        public Output<int?> CustomUrlsCount { get; private set; } = null!;

        [Output("dbCategorizedUrls")]
        public Output<ImmutableArray<string>> DbCategorizedUrls { get; private set; } = null!;

        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        [Output("editable")]
        public Output<bool?> Editable { get; private set; } = null!;

        [Output("ipRanges")]
        public Output<ImmutableArray<string>> IpRanges { get; private set; } = null!;

        [Output("ipRangesRetainingParentCategory")]
        public Output<ImmutableArray<string>> IpRangesRetainingParentCategory { get; private set; } = null!;

        [Output("ipRangesRetainingParentCategoryCount")]
        public Output<int?> IpRangesRetainingParentCategoryCount { get; private set; } = null!;

        [Output("keywords")]
        public Output<ImmutableArray<string>> Keywords { get; private set; } = null!;

        [Output("keywordsRetainingParentCategory")]
        public Output<ImmutableArray<string>> KeywordsRetainingParentCategory { get; private set; } = null!;

        [Output("regexPatterns")]
        public Output<ImmutableArray<string>> RegexPatterns { get; private set; } = null!;

        [Output("regexPatternsRetainingParentCategory")]
        public Output<ImmutableArray<string>> RegexPatternsRetainingParentCategory { get; private set; } = null!;

        [Output("scopes")]
        public Output<ImmutableArray<Outputs.UrlCategoryScopeInput>> Scopes { get; private set; } = null!;

        [Output("superCategory")]
        public Output<string?> SuperCategory { get; private set; } = null!;

        [Output("type")]
        public Output<string?> Type { get; private set; } = null!;

        [Output("urlKeywordCounts")]
        public Output<Outputs.UrlCategoryUrlKeywordCountsInput?> UrlKeywordCounts { get; private set; } = null!;

        [Output("urlType")]
        public Output<string?> UrlType { get; private set; } = null!;

        [Output("urls")]
        public Output<ImmutableArray<string>> Urls { get; private set; } = null!;

        [Output("urlsRetainingParentCategoryCount")]
        public Output<int?> UrlsRetainingParentCategoryCount { get; private set; } = null!;

        [Output("val")]
        public Output<int?> Val { get; private set; } = null!;


        /// <summary>
        /// Create a UrlCategory resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public UrlCategory(string name, UrlCategoryArgs? args = null, CustomResourceOptions? options = null)
            : base("zia:index:UrlCategory", name, args ?? new UrlCategoryArgs(), MakeResourceOptions(options, ""))
        {
        }

        private UrlCategory(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("zia:index:UrlCategory", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing UrlCategory resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static UrlCategory Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new UrlCategory(name, id, options);
        }
    }

    public sealed class UrlCategoryArgs : global::Pulumi.ResourceArgs
    {
        [Input("configuredName")]
        public Input<string>? ConfiguredName { get; set; }

        [Input("customCategory")]
        public Input<bool>? CustomCategory { get; set; }

        [Input("dbCategorizedUrls")]
        private InputList<string>? _dbCategorizedUrls;
        public InputList<string> DbCategorizedUrls
        {
            get => _dbCategorizedUrls ?? (_dbCategorizedUrls = new InputList<string>());
            set => _dbCategorizedUrls = value;
        }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("ipRanges")]
        private InputList<string>? _ipRanges;
        public InputList<string> IpRanges
        {
            get => _ipRanges ?? (_ipRanges = new InputList<string>());
            set => _ipRanges = value;
        }

        [Input("ipRangesRetainingParentCategory")]
        private InputList<string>? _ipRangesRetainingParentCategory;
        public InputList<string> IpRangesRetainingParentCategory
        {
            get => _ipRangesRetainingParentCategory ?? (_ipRangesRetainingParentCategory = new InputList<string>());
            set => _ipRangesRetainingParentCategory = value;
        }

        [Input("keywords")]
        private InputList<string>? _keywords;
        public InputList<string> Keywords
        {
            get => _keywords ?? (_keywords = new InputList<string>());
            set => _keywords = value;
        }

        [Input("keywordsRetainingParentCategory")]
        private InputList<string>? _keywordsRetainingParentCategory;
        public InputList<string> KeywordsRetainingParentCategory
        {
            get => _keywordsRetainingParentCategory ?? (_keywordsRetainingParentCategory = new InputList<string>());
            set => _keywordsRetainingParentCategory = value;
        }

        [Input("regexPatterns")]
        private InputList<string>? _regexPatterns;
        public InputList<string> RegexPatterns
        {
            get => _regexPatterns ?? (_regexPatterns = new InputList<string>());
            set => _regexPatterns = value;
        }

        [Input("regexPatternsRetainingParentCategory")]
        private InputList<string>? _regexPatternsRetainingParentCategory;
        public InputList<string> RegexPatternsRetainingParentCategory
        {
            get => _regexPatternsRetainingParentCategory ?? (_regexPatternsRetainingParentCategory = new InputList<string>());
            set => _regexPatternsRetainingParentCategory = value;
        }

        [Input("scopes")]
        private InputList<Inputs.UrlCategoryScopeInputArgs>? _scopes;
        public InputList<Inputs.UrlCategoryScopeInputArgs> Scopes
        {
            get => _scopes ?? (_scopes = new InputList<Inputs.UrlCategoryScopeInputArgs>());
            set => _scopes = value;
        }

        [Input("superCategory")]
        public Input<string>? SuperCategory { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("urlKeywordCounts")]
        public Input<Inputs.UrlCategoryUrlKeywordCountsInputArgs>? UrlKeywordCounts { get; set; }

        [Input("urlType")]
        public Input<string>? UrlType { get; set; }

        [Input("urls")]
        private InputList<string>? _urls;
        public InputList<string> Urls
        {
            get => _urls ?? (_urls = new InputList<string>());
            set => _urls = value;
        }

        public UrlCategoryArgs()
        {
        }
        public static new UrlCategoryArgs Empty => new UrlCategoryArgs();
    }
}
