// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zia.Outputs
{

    [OutputType]
    public sealed class DatacenterInfo
    {
        public readonly string City;
        public readonly int CreateTime;
        public readonly bool DontProvision;
        public readonly bool DontPublish;
        public readonly int DownloadBandwidth;
        public readonly bool ForFutureUse;
        public readonly bool GovOnly;
        public readonly int Id;
        public readonly int LastModifiedTime;
        public readonly int Lat;
        public readonly double Latitude;
        public readonly int Longi;
        public readonly double Longitude;
        public readonly bool ManagedBcp;
        public readonly string Name;
        public readonly bool NotReadyForUse;
        public readonly bool OwnedByCustomer;
        public readonly string Provider;
        public readonly bool RegionalSurcharge;
        public readonly bool ThirdPartyCloud;
        public readonly string Timezone;
        public readonly int UploadBandwidth;
        public readonly bool Virtual;

        [OutputConstructor]
        private DatacenterInfo(
            string city,

            int createTime,

            bool dontProvision,

            bool dontPublish,

            int downloadBandwidth,

            bool forFutureUse,

            bool govOnly,

            int id,

            int lastModifiedTime,

            int lat,

            double latitude,

            int longi,

            double longitude,

            bool managedBcp,

            string name,

            bool notReadyForUse,

            bool ownedByCustomer,

            string provider,

            bool regionalSurcharge,

            bool thirdPartyCloud,

            string timezone,

            int uploadBandwidth,

            bool @virtual)
        {
            City = city;
            CreateTime = createTime;
            DontProvision = dontProvision;
            DontPublish = dontPublish;
            DownloadBandwidth = downloadBandwidth;
            ForFutureUse = forFutureUse;
            GovOnly = govOnly;
            Id = id;
            LastModifiedTime = lastModifiedTime;
            Lat = lat;
            Latitude = latitude;
            Longi = longi;
            Longitude = longitude;
            ManagedBcp = managedBcp;
            Name = name;
            NotReadyForUse = notReadyForUse;
            OwnedByCustomer = ownedByCustomer;
            Provider = provider;
            RegionalSurcharge = regionalSurcharge;
            ThirdPartyCloud = thirdPartyCloud;
            Timezone = timezone;
            UploadBandwidth = uploadBandwidth;
            Virtual = @virtual;
        }
    }
}
