// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.zia.zia;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.zia.zia.ForwardingControlZpaGatewayArgs;
import com.zia.zia.Utilities;
import com.zia.zia.outputs.ZpaGatewayAppSegmentInput;
import com.zia.zia.outputs.ZpaServerGroupInput;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * The zia.ForwardingControlZpaGateway resource manages forwarding control ZPA gateway configurations in the
 * Zscaler Internet Access (ZIA) cloud. ZPA gateways are used in forwarding control rules to direct traffic
 * to Zscaler Private Access (ZPA) application segments through ZPA server groups.
 * 
 * ## Example Usage
 * 
 * ## Import
 * 
 * An existing forwarding control ZPA gateway can be imported using its ID, e.g.
 * 
 * ```sh
 * $ pulumi import zia:index:ForwardingControlZpaGateway example 12345
 * ```
 * 
 */
@ResourceType(type="zia:index:ForwardingControlZpaGateway")
public class ForwardingControlZpaGateway extends com.pulumi.resources.CustomResource {
    /**
     * Description of the ZPA gateway.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return Description of the ZPA gateway.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * The unique identifier for the ZPA gateway assigned by the ZIA cloud.
     * 
     */
    @Export(name="gatewayId", refs={Integer.class}, tree="[0]")
    private Output<Integer> gatewayId;

    /**
     * @return The unique identifier for the ZPA gateway assigned by the ZIA cloud.
     * 
     */
    public Output<Integer> gatewayId() {
        return this.gatewayId;
    }
    /**
     * Name of the ZPA gateway.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> name;

    /**
     * @return Name of the ZPA gateway.
     * 
     */
    public Output<Optional<String>> name() {
        return Codegen.optional(this.name);
    }
    /**
     * The gateway type. Accepted values: &#39;ZPA&#39; or &#39;ECZPA&#39;.
     * 
     */
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> type;

    /**
     * @return The gateway type. Accepted values: &#39;ZPA&#39; or &#39;ECZPA&#39;.
     * 
     */
    public Output<Optional<String>> type() {
        return Codegen.optional(this.type);
    }
    /**
     * List of ZPA application segments associated with the gateway.
     * 
     */
    @Export(name="zpaAppSegments", refs={List.class,ZpaGatewayAppSegmentInput.class}, tree="[0,1]")
    private Output</* @Nullable */ List<ZpaGatewayAppSegmentInput>> zpaAppSegments;

    /**
     * @return List of ZPA application segments associated with the gateway.
     * 
     */
    public Output<Optional<List<ZpaGatewayAppSegmentInput>>> zpaAppSegments() {
        return Codegen.optional(this.zpaAppSegments);
    }
    /**
     * The ZPA server group associated with the gateway.
     * 
     */
    @Export(name="zpaServerGroup", refs={ZpaServerGroupInput.class}, tree="[0]")
    private Output</* @Nullable */ ZpaServerGroupInput> zpaServerGroup;

    /**
     * @return The ZPA server group associated with the gateway.
     * 
     */
    public Output<Optional<ZpaServerGroupInput>> zpaServerGroup() {
        return Codegen.optional(this.zpaServerGroup);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ForwardingControlZpaGateway(java.lang.String name) {
        this(name, ForwardingControlZpaGatewayArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ForwardingControlZpaGateway(java.lang.String name, @Nullable ForwardingControlZpaGatewayArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ForwardingControlZpaGateway(java.lang.String name, @Nullable ForwardingControlZpaGatewayArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("zia:index:ForwardingControlZpaGateway", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ForwardingControlZpaGateway(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("zia:index:ForwardingControlZpaGateway", name, null, makeResourceOptions(options, id), false);
    }

    private static ForwardingControlZpaGatewayArgs makeArgs(@Nullable ForwardingControlZpaGatewayArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ForwardingControlZpaGatewayArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/zscaler")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ForwardingControlZpaGateway get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ForwardingControlZpaGateway(name, id, options);
    }
}
