// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.zia.zia;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.zia.zia.UrlCategoryPredefinedArgs;
import com.zia.zia.Utilities;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="zia:index:UrlCategoryPredefined")
public class UrlCategoryPredefined extends com.pulumi.resources.CustomResource {
    @Export(name="categoryId", refs={String.class}, tree="[0]")
    private Output<String> categoryId;

    public Output<String> categoryId() {
        return this.categoryId;
    }
    @Export(name="configuredName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> configuredName;

    public Output<Optional<String>> configuredName() {
        return Codegen.optional(this.configuredName);
    }
    @Export(name="customIpRangesCount", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> customIpRangesCount;

    public Output<Optional<Integer>> customIpRangesCount() {
        return Codegen.optional(this.customIpRangesCount);
    }
    @Export(name="customUrlsCount", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> customUrlsCount;

    public Output<Optional<Integer>> customUrlsCount() {
        return Codegen.optional(this.customUrlsCount);
    }
    @Export(name="dbCategorizedUrls", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> dbCategorizedUrls;

    public Output<Optional<List<String>>> dbCategorizedUrls() {
        return Codegen.optional(this.dbCategorizedUrls);
    }
    @Export(name="editable", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> editable;

    public Output<Optional<Boolean>> editable() {
        return Codegen.optional(this.editable);
    }
    @Export(name="ipRanges", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> ipRanges;

    public Output<Optional<List<String>>> ipRanges() {
        return Codegen.optional(this.ipRanges);
    }
    @Export(name="ipRangesRetainingParentCategory", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> ipRangesRetainingParentCategory;

    public Output<Optional<List<String>>> ipRangesRetainingParentCategory() {
        return Codegen.optional(this.ipRangesRetainingParentCategory);
    }
    @Export(name="ipRangesRetainingParentCategoryCount", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> ipRangesRetainingParentCategoryCount;

    public Output<Optional<Integer>> ipRangesRetainingParentCategoryCount() {
        return Codegen.optional(this.ipRangesRetainingParentCategoryCount);
    }
    @Export(name="keywords", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> keywords;

    public Output<Optional<List<String>>> keywords() {
        return Codegen.optional(this.keywords);
    }
    @Export(name="keywordsRetainingParentCategory", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> keywordsRetainingParentCategory;

    public Output<Optional<List<String>>> keywordsRetainingParentCategory() {
        return Codegen.optional(this.keywordsRetainingParentCategory);
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="superCategory", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> superCategory;

    public Output<Optional<String>> superCategory() {
        return Codegen.optional(this.superCategory);
    }
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> type;

    public Output<Optional<String>> type() {
        return Codegen.optional(this.type);
    }
    @Export(name="urlType", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> urlType;

    public Output<Optional<String>> urlType() {
        return Codegen.optional(this.urlType);
    }
    @Export(name="urls", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> urls;

    public Output<Optional<List<String>>> urls() {
        return Codegen.optional(this.urls);
    }
    @Export(name="urlsRetainingParentCategoryCount", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> urlsRetainingParentCategoryCount;

    public Output<Optional<Integer>> urlsRetainingParentCategoryCount() {
        return Codegen.optional(this.urlsRetainingParentCategoryCount);
    }
    @Export(name="val", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> val;

    public Output<Optional<Integer>> val() {
        return Codegen.optional(this.val);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public UrlCategoryPredefined(java.lang.String name) {
        this(name, UrlCategoryPredefinedArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public UrlCategoryPredefined(java.lang.String name, UrlCategoryPredefinedArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public UrlCategoryPredefined(java.lang.String name, UrlCategoryPredefinedArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("zia:index:UrlCategoryPredefined", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private UrlCategoryPredefined(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("zia:index:UrlCategoryPredefined", name, null, makeResourceOptions(options, id), false);
    }

    private static UrlCategoryPredefinedArgs makeArgs(UrlCategoryPredefinedArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? UrlCategoryPredefinedArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static UrlCategoryPredefined get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new UrlCategoryPredefined(name, id, options);
    }
}
