// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.zia.zia;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.zia.zia.inputs.WorkloadGroupExpressionJsonInputArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class WorkloadGroupArgs extends com.pulumi.resources.ResourceArgs {

    public static final WorkloadGroupArgs Empty = new WorkloadGroupArgs();

    /**
     * Description of the workload group.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Description of the workload group.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The expression JSON that defines the workload group matching criteria using tag expressions.
     * 
     */
    @Import(name="expressionJson")
    private @Nullable Output<WorkloadGroupExpressionJsonInputArgs> expressionJson;

    /**
     * @return The expression JSON that defines the workload group matching criteria using tag expressions.
     * 
     */
    public Optional<Output<WorkloadGroupExpressionJsonInputArgs>> expressionJson() {
        return Optional.ofNullable(this.expressionJson);
    }

    /**
     * Name of the workload group.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Name of the workload group.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    private WorkloadGroupArgs() {}

    private WorkloadGroupArgs(WorkloadGroupArgs $) {
        this.description = $.description;
        this.expressionJson = $.expressionJson;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(WorkloadGroupArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private WorkloadGroupArgs $;

        public Builder() {
            $ = new WorkloadGroupArgs();
        }

        public Builder(WorkloadGroupArgs defaults) {
            $ = new WorkloadGroupArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param description Description of the workload group.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Description of the workload group.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param expressionJson The expression JSON that defines the workload group matching criteria using tag expressions.
         * 
         * @return builder
         * 
         */
        public Builder expressionJson(@Nullable Output<WorkloadGroupExpressionJsonInputArgs> expressionJson) {
            $.expressionJson = expressionJson;
            return this;
        }

        /**
         * @param expressionJson The expression JSON that defines the workload group matching criteria using tag expressions.
         * 
         * @return builder
         * 
         */
        public Builder expressionJson(WorkloadGroupExpressionJsonInputArgs expressionJson) {
            return expressionJson(Output.of(expressionJson));
        }

        /**
         * @param name Name of the workload group.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of the workload group.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public WorkloadGroupArgs build() {
            return $;
        }
    }

}
