// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * The zia_fw_network_service resource manages firewall network services in the Zscaler Internet Access (ZIA) cloud service. Network services define the TCP/UDP port ranges used in firewall filtering rules.
 *
 * For more information, see the [ZIA Firewall Policies documentation](https://help.zscaler.com/zia/firewall-policies).
 *
 * ## Example Usage
 * ### Basic Network Service
 *
 * ```typescript
 * import * as zia from "@bdzscaler/pulumi-zia";
 *
 * const example = new zia.FwNetworkService("example", {
 *     name: "Example Network Service",
 *     description: "Custom network service",
 *     destTcpPorts: [
 *         { start: 443, end: 443 },
 *         { start: 8080, end: 8090 },
 *     ],
 * });
 * ```
 *
 * ## Import
 *
 * An existing network service can be imported using its resource ID, e.g.
 *
 * ```sh
 * $ pulumi import zia:index:FwNetworkService example 12345
 * ```
 */
export class FwNetworkService extends pulumi.CustomResource {
    /**
     * Get an existing FwNetworkService resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): FwNetworkService {
        return new FwNetworkService(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'zia:index:FwNetworkService';

    /**
     * Returns true if the given object is an instance of FwNetworkService.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FwNetworkService {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FwNetworkService.__pulumiType;
    }

    /**
     * Additional information about the network service.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Destination TCP port ranges. Each entry specifies a start and end port.
     */
    declare public readonly destTcpPorts: pulumi.Output<outputs.NetworkPortInput[] | undefined>;
    /**
     * Destination UDP port ranges. Each entry specifies a start and end port.
     */
    declare public readonly destUdpPorts: pulumi.Output<outputs.NetworkPortInput[] | undefined>;
    /**
     * Indicates whether the name is a localization tag.
     */
    declare public readonly isNameL10nTag: pulumi.Output<boolean | undefined>;
    /**
     * The name of the network service.
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * The system-generated ID of the network service.
     */
    declare public /*out*/ readonly networkServiceId: pulumi.Output<number>;
    /**
     * Source TCP port ranges. Each entry specifies a start and end port.
     */
    declare public readonly srcTcpPorts: pulumi.Output<outputs.NetworkPortInput[] | undefined>;
    /**
     * Source UDP port ranges. Each entry specifies a start and end port.
     */
    declare public readonly srcUdpPorts: pulumi.Output<outputs.NetworkPortInput[] | undefined>;
    /**
     * The tag associated with the network service.
     */
    declare public readonly tag: pulumi.Output<string | undefined>;
    /**
     * The network service type. Valid values: `STANDARD`, `PREDEFINED`, `CUSTOM`.
     */
    declare public readonly type: pulumi.Output<string | undefined>;

    /**
     * Create a FwNetworkService resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: FwNetworkServiceArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["description"] = args?.description;
            resourceInputs["destTcpPorts"] = args?.destTcpPorts;
            resourceInputs["destUdpPorts"] = args?.destUdpPorts;
            resourceInputs["isNameL10nTag"] = args?.isNameL10nTag;
            resourceInputs["name"] = args?.name;
            resourceInputs["srcTcpPorts"] = args?.srcTcpPorts;
            resourceInputs["srcUdpPorts"] = args?.srcUdpPorts;
            resourceInputs["tag"] = args?.tag;
            resourceInputs["type"] = args?.type;
            resourceInputs["networkServiceId"] = undefined /*out*/;
        } else {
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["destTcpPorts"] = undefined /*out*/;
            resourceInputs["destUdpPorts"] = undefined /*out*/;
            resourceInputs["isNameL10nTag"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["networkServiceId"] = undefined /*out*/;
            resourceInputs["srcTcpPorts"] = undefined /*out*/;
            resourceInputs["srcUdpPorts"] = undefined /*out*/;
            resourceInputs["tag"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FwNetworkService.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a FwNetworkService resource.
 */
export interface FwNetworkServiceArgs {
    /**
     * Additional information about the network service.
     */
    description?: pulumi.Input<string>;
    /**
     * Destination TCP port ranges. Each entry specifies a start and end port.
     */
    destTcpPorts?: pulumi.Input<pulumi.Input<inputs.NetworkPortInputArgs>[]>;
    /**
     * Destination UDP port ranges. Each entry specifies a start and end port.
     */
    destUdpPorts?: pulumi.Input<pulumi.Input<inputs.NetworkPortInputArgs>[]>;
    /**
     * Indicates whether the name is a localization tag.
     */
    isNameL10nTag?: pulumi.Input<boolean>;
    /**
     * The name of the network service.
     */
    name?: pulumi.Input<string>;
    /**
     * Source TCP port ranges. Each entry specifies a start and end port.
     */
    srcTcpPorts?: pulumi.Input<pulumi.Input<inputs.NetworkPortInputArgs>[]>;
    /**
     * Source UDP port ranges. Each entry specifies a start and end port.
     */
    srcUdpPorts?: pulumi.Input<pulumi.Input<inputs.NetworkPortInputArgs>[]>;
    /**
     * The tag associated with the network service.
     */
    tag?: pulumi.Input<string>;
    /**
     * The network service type. Valid values: `STANDARD`, `PREDEFINED`, `CUSTOM`.
     */
    type?: pulumi.Input<string>;
}
