// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * * [Official documentation](https://help.zscaler.com/zia/about-exact-data-match)
 * * [API documentation](https://help.zscaler.com/zia/data-loss-prevention#/dlpExactDataMatchSchemas-get)
 *
 * Use the **zia_dlp_edm_schema** data source to get information about a the list of DLP Exact Data Match (EDM) templates in the Zscaler Internet Access cloud or via the API.
 *
 * ## Example Usage
 */
export function getDLPEDMSchema(args?: GetDLPEDMSchemaArgs, opts?: pulumi.InvokeOptions): Promise<GetDLPEDMSchemaResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zia:index/getDLPEDMSchema:getDLPEDMSchema", {
        "projectName": args.projectName,
    }, opts);
}

/**
 * A collection of arguments for invoking getDLPEDMSchema.
 */
export interface GetDLPEDMSchemaArgs {
    projectName?: string;
}

/**
 * A collection of values returned by getDLPEDMSchema.
 */
export interface GetDLPEDMSchemaResult {
    readonly cellsUsed: number;
    readonly createdBies: outputs.GetDLPEDMSchemaCreatedBy[];
    readonly edmClients: outputs.GetDLPEDMSchemaEdmClient[];
    readonly fileName: string;
    readonly fileUploadStatus: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly lastModifiedBies: outputs.GetDLPEDMSchemaLastModifiedBy[];
    readonly lastModifiedTime: number;
    readonly origColCount: number;
    readonly originalFileName: string;
    readonly projectName?: string;
    readonly revision: number;
    readonly schedulePresent: boolean;
    readonly schedules: outputs.GetDLPEDMSchemaSchedule[];
    readonly schemaActive: boolean;
    readonly schemaId: number;
    readonly tokenLists: outputs.GetDLPEDMSchemaTokenList[];
}
/**
 * * [Official documentation](https://help.zscaler.com/zia/about-exact-data-match)
 * * [API documentation](https://help.zscaler.com/zia/data-loss-prevention#/dlpExactDataMatchSchemas-get)
 *
 * Use the **zia_dlp_edm_schema** data source to get information about a the list of DLP Exact Data Match (EDM) templates in the Zscaler Internet Access cloud or via the API.
 *
 * ## Example Usage
 */
export function getDLPEDMSchemaOutput(args?: GetDLPEDMSchemaOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDLPEDMSchemaResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("zia:index/getDLPEDMSchema:getDLPEDMSchema", {
        "projectName": args.projectName,
    }, opts);
}

/**
 * A collection of arguments for invoking getDLPEDMSchema.
 */
export interface GetDLPEDMSchemaOutputArgs {
    projectName?: pulumi.Input<string>;
}
