// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Use the **zia_firewall_filtering_ip_source_groups** data source to get information about ip source groups available in the Zscaler Internet Access cloud firewall. This data source can then be associated with a ZIA firewall filtering rule.
 *
 * ## Example Usage
 */
export function getFirewallFilteringSourceIPGroups(args?: GetFirewallFilteringSourceIPGroupsArgs, opts?: pulumi.InvokeOptions): Promise<GetFirewallFilteringSourceIPGroupsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zia:index/getFirewallFilteringSourceIPGroups:getFirewallFilteringSourceIPGroups", {
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getFirewallFilteringSourceIPGroups.
 */
export interface GetFirewallFilteringSourceIPGroupsArgs {
    /**
     * The ID of the ip source group resource.
     */
    id?: number;
    /**
     * The name of the ip source group to be exported.
     */
    name?: string;
}

/**
 * A collection of values returned by getFirewallFilteringSourceIPGroups.
 */
export interface GetFirewallFilteringSourceIPGroupsResult {
    /**
     * (String)
     */
    readonly description: string;
    /**
     * The ID of this resource.
     */
    readonly id: number;
    /**
     * (List of String)
     */
    readonly ipAddresses: string[];
    readonly name: string;
}
/**
 * Use the **zia_firewall_filtering_ip_source_groups** data source to get information about ip source groups available in the Zscaler Internet Access cloud firewall. This data source can then be associated with a ZIA firewall filtering rule.
 *
 * ## Example Usage
 */
export function getFirewallFilteringSourceIPGroupsOutput(args?: GetFirewallFilteringSourceIPGroupsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetFirewallFilteringSourceIPGroupsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("zia:index/getFirewallFilteringSourceIPGroups:getFirewallFilteringSourceIPGroups", {
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getFirewallFilteringSourceIPGroups.
 */
export interface GetFirewallFilteringSourceIPGroupsOutputArgs {
    /**
     * The ID of the ip source group resource.
     */
    id?: pulumi.Input<number>;
    /**
     * The name of the ip source group to be exported.
     */
    name?: pulumi.Input<string>;
}
