// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The zia.NssServer resource manages NSS (Nanolog Streaming Service) server configurations in the
 * Zscaler Internet Access (ZIA) cloud. NSS servers are used to stream logs from ZIA to external SIEM
 * or log management systems.
 *
 * ## Example Usage
 * ### Basic NSS Server
 *
 * ```typescript
 * import * as zia from "@bdzscaler/pulumi-zia";
 *
 * const example = new zia.NssServer("example", {
 *     name: "Example NSS Server",
 *     status: "ENABLED",
 *     type: "NSS_FOR_FIREWALL",
 * });
 * ```
 *
 * ## Import
 *
 * An existing NSS server can be imported using its ID, e.g.
 *
 * ```sh
 * $ pulumi import zia:index:NssServer example 12345
 * ```
 */
export class NssServer extends pulumi.CustomResource {
    /**
     * Get an existing NssServer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): NssServer {
        return new NssServer(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'zia:index:NssServer';

    /**
     * Returns true if the given object is an instance of NssServer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NssServer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NssServer.__pulumiType;
    }

    /**
     * The ICAP server ID associated with the NSS server.
     */
    declare public readonly icapSvrId: pulumi.Output<number | undefined>;
    /**
     * Name of the NSS server.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The unique identifier for the NSS server assigned by the ZIA cloud.
     */
    declare public /*out*/ readonly nssId: pulumi.Output<number>;
    /**
     * The status of the NSS server. Accepted values: 'ENABLED' or 'DISABLED'. Default: 'ENABLED'.
     */
    declare public readonly status: pulumi.Output<string | undefined>;
    /**
     * The NSS server type. Accepted values: 'NSS_FOR_FIREWALL', 'NSS_FOR_WEB'. Default: 'NSS_FOR_FIREWALL'.
     */
    declare public readonly type: pulumi.Output<string | undefined>;

    /**
     * Create a NssServer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NssServerArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["icapSvrId"] = args?.icapSvrId;
            resourceInputs["name"] = args?.name;
            resourceInputs["status"] = args?.status;
            resourceInputs["type"] = args?.type;
            resourceInputs["nssId"] = undefined /*out*/;
        } else {
            resourceInputs["icapSvrId"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["nssId"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NssServer.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a NssServer resource.
 */
export interface NssServerArgs {
    /**
     * The ICAP server ID associated with the NSS server.
     */
    icapSvrId?: pulumi.Input<number>;
    /**
     * Name of the NSS server.
     */
    name: pulumi.Input<string>;
    /**
     * The status of the NSS server. Accepted values: 'ENABLED' or 'DISABLED'. Default: 'ENABLED'.
     */
    status?: pulumi.Input<string>;
    /**
     * The NSS server type. Accepted values: 'NSS_FOR_FIREWALL', 'NSS_FOR_WEB'. Default: 'NSS_FOR_FIREWALL'.
     */
    type?: pulumi.Input<string>;
}
