// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The zia_security_policy_settings resource manages the whitelist and blacklist URL configuration for the ZIA security policy. This is a singleton resource that controls which URLs are always allowed (whitelisted) or always blocked (blacklisted) across the organization.
 *
 * For more information, see the [ZIA Security Policy Settings documentation](https://help.zscaler.com/zia/configuring-security-policy).
 *
 * ## Example Usage
 * ### Basic Security Policy Settings
 *
 * ```typescript
 * import * as zia from "@bdzscaler/pulumi-zia";
 *
 * const example = new zia.SecurityPolicySettings("example", {
 *     whitelistUrls: [
 *         "example.com",
 *         "trusted-site.org",
 *     ],
 *     blacklistUrls: [
 *         "malicious-site.com",
 *         "phishing-site.net",
 *     ],
 * });
 * ```
 *
 * > This is a singleton resource. Import is not applicable.
 */
export class SecurityPolicySettings extends pulumi.CustomResource {
    /**
     * Get an existing SecurityPolicySettings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): SecurityPolicySettings {
        return new SecurityPolicySettings(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'zia:index:SecurityPolicySettings';

    /**
     * Returns true if the given object is an instance of SecurityPolicySettings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecurityPolicySettings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecurityPolicySettings.__pulumiType;
    }

    /**
     * List of URLs that are always blocked (blacklisted) by the security policy.
     */
    declare public readonly blacklistUrls: pulumi.Output<string[] | undefined>;
    /**
     * The internal resource identifier for the security policy settings.
     */
    declare public /*out*/ readonly resourceId: pulumi.Output<string>;
    /**
     * List of URLs that are always allowed (whitelisted) by the security policy.
     */
    declare public readonly whitelistUrls: pulumi.Output<string[] | undefined>;

    /**
     * Create a SecurityPolicySettings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SecurityPolicySettingsArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["blacklistUrls"] = args?.blacklistUrls;
            resourceInputs["whitelistUrls"] = args?.whitelistUrls;
            resourceInputs["resourceId"] = undefined /*out*/;
        } else {
            resourceInputs["blacklistUrls"] = undefined /*out*/;
            resourceInputs["resourceId"] = undefined /*out*/;
            resourceInputs["whitelistUrls"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecurityPolicySettings.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a SecurityPolicySettings resource.
 */
export interface SecurityPolicySettingsArgs {
    /**
     * List of URLs that are always blocked (blacklisted) by the security policy.
     */
    blacklistUrls?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * List of URLs that are always allowed (whitelisted) by the security policy.
     */
    whitelistUrls?: pulumi.Input<pulumi.Input<string>[]>;
}
